### ISSUE TITLE
migrating up from previous version, getDb() on a non-object

### ISSUE THREAD

**Issue by cloudswitch** [bedezign/yii2-audit#102]
Hi,

when migrating up from previous version:

PS C:\Windows\system32> cd D:\wamp\www\basic
PS D:\wamp\www\basic> .\yii migrate --migrationPath=@bedezign/yii2/audit/migrations/0.1-0.2
Yii Migration Tool (based on Yii v2.0.4)

Total 11 new migrations to be applied:
        m150622_000001_update_audit_entry
        m150622_000002_update_audit_entry
        m150622_000003_update_audit_entry
        m150622_000003_update_audit_error
        m150623_000001_audit_id_to_entry_id
        m150623_000002_drop_superfluous_fields
        m150623_000003_add_audit_entry_ajax
        m150625_000001_update_audit_entry
        m150625_000002_update_audit_data
        m150625_000003_update_audit_trail
        m150625_000004_fake_new_migrations

Apply the above migrations? (yes|no) [no]:y
*** applying m150622_000001_update_audit_entry
    > add column request_method varchar(255) NULL AFTER memory_max to table {{%audit_entry}} ... done (time: 0.047s)
    > create index idx_audit_entry_request_method on {{%audit_entry}} (request_method) ... done (time: 0.031s)
    > filling 'request_method' from data ...PHP Fatal Error 'yii\base\ErrorException' with message 'Call to a member function getDb() on a non-object'

in D:\wamp\www\basic\vendor\bedezign\yii2-audit\src\components\db\ActiveRecord.php:31

Stack trace:
#0 D:\wamp\www\basic\vendor\yiisoft\yii2\db\BatchQueryResult.php(138): yii\db\ActiveQuery->createCommand()
#1 D:\wamp\www\basic\vendor\yiisoft\yii2\db\BatchQueryResult.php(112): yii\db\BatchQueryResult->fetchData()
#2 D:\wamp\www\basic\vendor\yiisoft\yii2\db\BatchQueryResult.php(102): yii\db\BatchQueryResult->next()
#3 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(16): yii\db\BatchQueryResult->rew
ind()
#4 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(492): m150622_000001_update_audit
_entry->up()
#5 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(129): yii\console\controllers\Bas
eMigrateController->migrateUp()
#6 D:\wamp\www\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): yii\console\controllers\BaseMigrateController->actio
nUp()
#7 D:\wamp\www\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array:{D:\wamp\www\basic\vendor\yii
soft\yii2\base\InlineAction.php:55}()
#8 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams()
#9 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction()
#10 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction()
#11 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction()
#12 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction()
#13 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest()
#14 D:\wamp\www\basic\yii(23): yii\base\Application->run()
#15 {main}

**Comment by cloudswitch** [comment]
I have deleted all old tables and migrations work now

**Comment by Blizzke** [comment]
Sorry about the problems you had. 

Truth of the matter is that we've tried to keep the scripts pre 1.0 compatible to get to the db structure for 1.0, but that the way data is stored was completely overhauled and the newest versions can't read the old data. 

So your decision to re-create the tables is the most logical and and the way to go. As a matter of fact, we should probably completely remove the old migration scripts, since the added use is practically zero.

**Comment by cloudswitch** [comment]
no no, no problem, just as info.
