### ISSUE TITLE
Error filter generation and indexes

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#103]
Right now the filter dropdown for the error list is based on a partial-index on the text field, it should actually base itself on the hash to make a distinction in the values

**Comment by cornernote** [comment]
The only filter I see in there is on file, which is a full index.

The hash is based on `Helper::hash($error->message . $error->file . $error->line)`.

I don't think anything is required here.

**Comment by Blizzke** [comment]
Yeah I saw that pretty much after I created the issue. Left it open because I'm planning on using the hash to create a filter for both the file and the different messages at once, so its still relevant.
