### ISSUE TITLE
Make main index page for heroku

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#106]
Add some triggers for various audit scenarios there like mail, error, javascript, perhaps auditing and some links to the docs and a big "View audit data"-button

**Comment by cornernote** [comment]
we are capturing IP addresses, then showing them to other people... its hard not to

site/index should tell people this, and we ignore hits to site/index

**Comment by cornernote** [comment]
all done, just needs a curl demo

**Comment by Blizzke** [comment]
cURL demo added :)
