### ISSUE TITLE
Open file from error trace in storm

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#117]
https://plugins.jetbrains.com/plugin/6027?pr=phpStorm

Need to look into it and discuss

**Comment by cornernote** [comment]
Had a quick read.  Basically you run some kind of service on your PC, and then you can have links like `http://localhost:8091?message=models/User.php:123`, which will trigger phpStorm to open `User.php` and goto line 123.

Seems like a neat idea to add this to the stack lines on the errors.  What do you think?

**Comment by arogachev** [comment]
Plugin author recently updated [readme](https://github.com/Zolotov/RemoteCall#readme) with info that extension is not supported anymore
