### ISSUE TITLE
Use the extension with Phundament/app

### ISSUE THREAD

**Issue by Silver90** [bedezign/yii2-audit#123]
Hi,
I tried the extension with phundament/app and the the entry view don't show the data but only the title.
The load on my db work.

Sorry for my bad english.

**Comment by Blizzke** [comment]
I'm sorry but we're going to need more info... Is there an error in the log or whatnot? anything that indicates what went wrong? It's very hard to diagnose an issue without any information except for "it doesn't work"

**Comment by Silver90** [comment]
Strangely it does not return any error . I just can not view the data in the Entry page but other pages viewing them properly .
![audit](https://cloud.githubusercontent.com/assets/12183231/9034580/26677c2c-39d1-11e5-9fd9-5706da52b41c.png)
![entry](https://cloud.githubusercontent.com/assets/12183231/9034581/27634bc4-39d1-11e5-9871-c2f49bdf0faf.png)

**Comment by Blizzke** [comment]
Perhaps you should try to enable `YII_DEBUG` in `index.php` and see if that yields any results. The fact that the entries is unstyled and that you actually have entries in the table (per your overview screenshot) indicates to me that it failed somewhere along the way. It might fail before it managed to output that info in your logfiles.

**Comment by Silver90** [comment]
Ok, i found the problem. In the index of Entry page i removed Javascript and Email on the GridView. I've probably done something wrong in the configuration because it does not record the javascript errors in my database. The e-
![entry](https://cloud.githubusercontent.com/assets/12183231/9035277/bb42efe8-39d6-11e5-85f0-eb590be1c2e3.png)
mail is not configured in my application

**Comment by Blizzke** [comment]
Those are all unfinished records, meaning it is crashing somewhere (the duration and memory for all but the last entry should be filled in)

**Comment by Blizzke** [comment]
And removing those columns should not be needed, if there aren't any errors/javascript records for the current entry it should just output nothing there, not crash.

**Comment by Silver90** [comment]
I know it's very strange . Now I see if I can find the cause of the problem and let you know.

**Comment by Blizzke** [comment]
Do you happen to have old data in your tables (pre 1.0)? If so: we changed the format and it is possible that it crashes while attempting to load that.

If you can't figure it out, it would be handy if you could get the module configuration and perhaps a dump of the audit tables, if they don't contain any private information yet.

**Comment by Blizzke** [comment]
Do you happen to have more information by any chance? If I don't hear anything back I will close the ticket.

**Comment by Blizzke** [comment]
Closing this as we cannot do anything without further info.
