### ISSUE TITLE
AuditTrailBehavior db option

### ISSUE THREAD

**Issue by karataserkan** [bedezign/yii2-audit#127]
Hİ,
I'm using multiple db's in my app. I store audit data in a different db. With Audit.php's db parameter it is working perfect but i have trouble with AuditTrailBehavior. It will help me to add db parameter for AuditTrailBehavior. 
If you say okay, i can add.

**Comment by Blizzke** [comment]
Hi,

`AuditTrailBehavior` doesn't need a DB as it does not do any database access on its own.
The trail data is always saved in the DB `Audit` is linked to, as that one contains the auditing tables.
Even if it would need the models` db, it gets linked to the relevant `ActiveRecord` class and that class has the DB for the model, but as I said, it's not needed. 

Am I misunderstanding what you need?

**Comment by karataserkan** [comment]
on line:227 and :236 in AuditTrailBehavior, Yii::$app->db->createCommand() called. Am I wrong? In my app, AuditTrailBehavior tried to save data to 'db' which is my core db. But I'm using audit with 'auditDb' database which I configure it in config.

**Comment by Blizzke** [comment]
You are right. My apologies. 
That is most definitely not the intention, the behavior should use the Audit::db instead. We'll take care of it. Thank you for bringing this to our attention.

**Comment by Blizzke** [comment]
Part of release [1.0.4](beddfac)
