### ISSUE TITLE
Error with package : 2amigos/yii2-chartjs-widget 2.0.0 requires bower-asset/chartjs 1.0.2 -> no matching package found.

### ISSUE THREAD

**Issue by ydakilux** [bedezign/yii2-audit#129]
Hi,

  I want to install the yii2-audit package but I get  the following error : 

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bedezign/yii2-audit 1.0.0 requires 2amigos/yii2-chartjs-widget 2.* -> satisfiable by 2amigos/yii2-chartjs-widget[2
.0.0].
    - bedezign/yii2-audit 1.0.1 requires 2amigos/yii2-chartjs-widget 2.* -> satisfiable by 2amigos/yii2-chartjs-widget[2
.0.0].
    - bedezign/yii2-audit 1.0.2 requires 2amigos/yii2-chartjs-widget 2.* -> satisfiable by 2amigos/yii2-chartjs-widget[2
.0.0].
    - bedezign/yii2-audit 1.0.3 requires 2amigos/yii2-chartjs-widget 2.* -> satisfiable by 2amigos/yii2-chartjs-widget[2
.0.0].
    - bedezign/yii2-audit 1.0.4 requires 2amigos/yii2-chartjs-widget 2.* -> satisfiable by 2amigos/yii2-chartjs-widget[2
.0.0].
    - 2amigos/yii2-chartjs-widget 2.0.0 requires bower-asset/chartjs 1.0.2 -> no matching package found.
    - Installation request for bedezign/yii2-audit ^1.0 -> satisfiable by bedezign/yii2-audit[1.0.0, 1.0.1, 1.0.2, 1.0.3
, 1.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

    Any help is welcome.
                      Kinds regards,
                                     Ydaki

**Comment by Blizzke** [comment]
I'm afraid that is not us, its a `2amigos/yii2-chartjs-widget`dependency that somehow can't be installed for you. Are you sure you have installed the `fxp/composer-asset-plugin` composer plugin globally as indicated in the Yii2 install procedure? That is the one managing all `bower` extensions.

**Comment by cornernote** [comment]
If you install `fxp/composer-asset-plugin` as one user (eg: root) then you are using a different user, it will cause this problem.

**Comment by Blizzke** [comment]
Not related to this module. Closing issue.

**Comment by ydakilux** [comment]
Thanks to Blizzke. 

   I have now installed the  <code> fxp/composer-asset-plugin </code> , then it worked well.

**Comment by Tarekajaj** [comment]
Hello,
I am getting the same error, updated fxp/composer-asset-plugin and tried to update bedezign/yii2-audit but couldn't update further than 1.0.6 because some unavailable dependencies
please advise.
