### ISSUE TITLE
confuse to use  Rolling Back to Last Version, Rolling Back to Any Version and undeleting

### ISSUE THREAD

**Issue by zainalawaludin** [bedezign/yii2-audit#134]
hi i try to implement Rolling Back to Last Version, Rolling Back to Any Version and undeleting, but i confuse where put the script on controller or  model ? could give me example?.. thanks

**Comment by cornernote** [comment]
The code can go in the controller or model, completely up to you as to how
you implement it. Personally I would put it in the model.

**Comment by zainalawaludin** [comment]
oke, and how to call this function if want to roll back or undeleting one of record field table ?

**Comment by cornernote** [comment]
The docs should explain it, but I'll reply tomorrow with an example. Only
have my phone at the moment and need a pc to respond properly.

**Comment by zainalawaludin** [comment]
oke thanks for u respon

**Comment by cornernote** [comment]
see here:
https://bedezign.github.io/yii2-audit/docs/trail-panel/

small example to revert the title field:

```php
use bedezign\yii2\audit\components\Version;

// load a post
$post = Post::findOne(1);

// load the last revision
$oldPost = Version::find($post->className(), $post->id);

// save the model
$post->title = $oldPost->title;
$post->save();
```

**Comment by zainalawaludin** [comment]
oke thanks. solved
