### ISSUE TITLE
how to use tabel without audit_data and audit_entry

### ISSUE THREAD

**Issue by zainalawaludin** [bedezign/yii2-audit#135]
hi is it possible to use this extension without table audit_data and audit_entry?.. cause if use this table, will big record on databased. thanks

**Comment by Blizzke** [comment]
No it is not. The entire extension is built around the `audit_entry` table. What is stored in the `audit_data` table can be limited by configuring what should be logged. By default most things are added there but you can disable this if you don't need them. Just check [the docs](https://bedezign.github.io/yii2-audit/docs/module-configuration/). All you need to do is override the `$panels`.
