### ISSUE TITLE
Module - Audit yii2 - Question (IgnoreActions)

### ISSUE THREAD

**Issue by rafaelwithoeft** [bedezign/yii2-audit#138]
Hello.
I'm trying to __ignore actions *["index", "view"]* of all controllers__, its possible? 
I have using like this:

> 'ignoreActions' => ['audit/*', 'debug/*', 'toolbar/*', 'index', 'view', '*/view', '*/index', '/index', '/view'];

But this not worked, you can help me?

Best Regards,
Thank you.

**Comment by Blizzke** [comment]
At this point there is no support for that specific scenario but it isn't really hard to add. I'll look into adding it, but cannot guarantee it will be the first week.

**Comment by rafaelwithoeft** [comment]
Thank you for your attention.

Best Regards,
Rafael

**Comment by Blizzke** [comment]
I've implemented support for * as prefix. Things like "*/index" should now work. For now it's only available if you follow master. I'll try to draft it in a release one of the next days.
