### ISSUE TITLE
DB cleanup cron job

### ISSUE THREAD

**Issue by SoleSS** [bedezign/yii2-audit#142]
0 2 * * * /var/www/.../basic/yii audit/cleanup --age=7

cron job is ok, but script asks for approve "Cleanup the above data? (yes|no) [no]"
and i can't find command argument to pass 'YES' to script...

**Comment by Blizzke** [comment]
Normally you tell the a CLI script to "not be interactive" (`cleanup --interactive=0 --age=7`) when running from the cron, but since we forgot to set the default answer to yes, at this point that won't work either. 
We'll make the modifications for you, thank you for bringing it to our attention.

**Comment by Blizzke** [comment]
Seems I was wrong: the default value is only value if you are running it interactively. So you should be able to get it to work as is:

`0 2 * * * /var/www/.../basic/yii audit/cleanup --age=7 --interactive=0`
