### ISSUE TITLE
Discussion: Are you planning to make this Async?

### ISSUE THREAD

**Issue by kushalhalder** [bedezign/yii2-audit#150]
Making this module Asynchronous can help people profile things on production data too.

**Comment by Blizzke** [comment]
Most of the data is actually written after the client request is terminated. Only the `AuditEntry` needs to be created as soon as anything is logged/an error occurs. We've kept this table very compact on purpose as to limit performance issues. So no, at this point the changes that need to be done to also get the creation of the entry being done after the request is just unrealistic compared to the gains.

**Comment by cornernote** [comment]
There was a lot of discussion about this in #67

**Comment by cornernote** [comment]
Also I was thinking about this, if you need extra performance you could run a sqlite database using an inmemory database then set the `Audit->db` attribute.  Then make a command that moves all the data to another database.

If you happen to do some performance checks on this please let me know what the overhead is.

**Comment by Blizzke** [comment]
`MySQL` also has in-memory tables, so you could even keep it within the same technology (if you are already using it) and just create a "dummy db" with the tables in memory as well.

**Comment by cornernote** [comment]
@kushalhalder,

Based on the solutions available (write to memory and create a script to move the data), it seems unworthwhile to implement async data writing.  I'll close this off, however if you feel there is reason to pursue with an async feature please feel free to comment.

Also if you happen to do any benchmarking please let us know your findings.

**Comment by kushalhalder** [comment]
We (at PharmEasy) already have a queueing system for yii2 in place, it's easy to plug in jobs. The workers are based on yii2 console commands and work asynchronously on a poll based mechanism. 

I liked your extension because of the simplicity and the overall architecture. But we do some more calculations before logging too. So I'll plug it in our queue and do some performance testing with it. I'll post my results here. 

A small suggestion, you guys should add a provision to do some more processing before the Audit entry stage. But your DB structure will change for that :/

**Comment by Blizzke** [comment]
You should easily be able to add your own custom data (which can also be extra processing) by simply adding your own panel. Add it to the module configuration and it will receive a call after the request for it to save its data.
