### ISSUE TITLE
checkAccess function

### ISSUE THREAD

**Issue by anek77713** [bedezign/yii2-audit#151]
```
    public static function checkAccess()
    {
        $audit = Audit::getInstance();
        if ($audit->accessIps === null && $audit->accessRoles === null && $audit->accessUsers === null) {
            return true;
        }
        if (self::checkAccessIps($audit->accessIps)) {
            return true;
        }
        if (self::checkAccessRoles($audit->accessRoles)) {
            return true;
        }
        if (self::checkAccessUsers($audit->accessUsers)) {
            return true;
        }
        return false;
    }
```

so the access control doesn't check all the params? but grants access if at least one of the params is ok ? that is strange, are you sure it has to work like that?

If my ip is ok - but im not "admin" with id 1 - I can still access audit..

**Comment by Blizzke** [comment]
Of course you are right. Past experience just indicated that people usually only use one at a time. 
If you need multiple "limitations" you are free to create a PR for it and we'll be sure to merge it in asap. 
If you need us to do it, we're all fairly busy at this time so not sure when we can allocate time for it.
