### ISSUE TITLE
Error on register MailEvent and ErrorEvent

### ISSUE THREAD

**Issue by markmarco16** [bedezign/yii2-audit#155]
I used yii2-audit on SqlServer 2008R2 by means of dblib and iODBC

	'dsn' => 'dblib:host=192.168.1.1;dbname=mydatabase',

My configuration is:

    'modules' => [
        'audit' => [
            'class' =>  'bedezign\yii2\audit\Audit',
             'accessRoles' => ['Administrator'],
             'compressData' => false,
             'layout' => '@app/views/layouts/main',
        ],
],

The problem is when trying insert record about MailEvent and Error Event say that:
SQLSTATE[HY000]: General error: 20018 Implicit conversion from data type varchar to binary is not allowed. Use the CONVERT function to run this query. [20018] (severity 16) [(null)]
The SQL being executed was: INSERT INTO [audit_mail] ([entry_id], [successful], [from], [to], [reply], [cc], [bcc], [subject], [text], [html], [data], [created]) VALUES (10098, 1, 'markmarco16@gmail.com', 'markmarco16@gmail.com', 'markmarco16@gmail.com', NULL, '', 'test test test test test test test test test test', 's:2995:"Message-ID: <a3d6a90b6bb5217b04389a502dc68738@localhost>
Date: Wed, 22 Jun 2016 10:53:42 -0400
Subject: test
From: markmarco16@gmail.com
Reply-To: Marco Da Silva <markmarco16@gmail.com>
To: Marco Da Silva <markmarco16@gmail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="_=_swift_v4_1466607222_a59862abb940902e966fb0495ef4eda5_=_" ......', '2016-06-22 10:53:48')

Apache/2.4.18 (Unix) PHP/5.5.34
Yii Framework/2.0.8

Some way rewrite the sentences for SQLSERVER?

Thank!

**Comment by Blizzke** [comment]
Hard to see where things went wrong. We do not support ODBC. Is there any way you can try to fix things yourself in the code to the point where it works for you and then come back here? Perhaps we can somehow work this into a PR together then. I'm unfortunately not in a position to test this myself as I do not use windows hardware.

**Comment by markmarco16** [comment]
thanks for your reply, I have decided to migrate the audit to a MySQL database
