### ISSUE TITLE
batch insert in AuditingBehavior

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#16]
Before visiting this awesome project I was starting my own Yii2 port.  I have a behavior that does audit with batch insert.  It means no need to create a model for each insert, and does all the inserts in 1 SQL command.

https://github.com/cornernote/yii2-audit/blob/master/src/behaviors/AuditFieldBehavior.php#L154

Could you incorporate that into your AuditingBehavior ?

**Comment by Blizzke** [comment]
Yeah that's probably a good idea. Especially in case of a lot of changes. I'll take a look at it.
