### ISSUE TITLE
audit/cleanup not working!

### ISSUE THREAD

**Issue by SoleSS** [bedezign/yii2-audit#169]
trying to automate audit/cleanup through crontab:
.../yii audit/cleanup --age=7 --interactive=0

no data is removed :(

**Comment by SoleSS** [comment]
yii2: 2.0.6
audit: 1.0.5

**Comment by Blizzke** [comment]
So do you have anything more for us to go on? 
"It doesn't work" is pretty much the least information we can get... 
How much data is in your tables? Are there any errors in the log? Is there any output produced?

**Comment by SoleSS** [comment]
64 Gb...
error: total number of locks exceeds the lock table size...

sorry :) looks like 7 days is still too much...
