### ISSUE TITLE
AuditTrailBehavior override propery break version control

### ISSUE THREAD

**Issue by ilgiz-badamshin** [bedezign/yii2-audit#173]
For example: class Profile has id and country_id, class Country has id and name.
I can override property country_id to save country.name instead id:
```
'override' => [
    'country_id' => [
        'tableName' => 'country',
        'searchField' => 'id',
        'returnField' => 'name'
    ]
]
```
If i get version of profile `$version = Version::find($profile->className(), $profile->id)`  then $version->country_id contains country.name, not id.

**Comment by cornernote** [comment]
Hello,

A similar feature was recently added, and planned for the 1.0.8 release.  Please see #171 for more information.

I think the documentation still needs to be updated.

**Comment by ilgiz-badamshin** [comment]
I use $override property from #173 and i reported about bug there.
If i get version of profile as `$version = Version::find($profile->className(), $profile->id)` , so `$version->country_id` contain country.**name**, but i expect there country.**id**. 
Maybe we should save origin id and use $override only to display diff?

**Comment by cornernote** [comment]
Yes, I see the issue.  The version control fails because the data in the audit_field is wrong.

Doing override only on the display has issues of it's own.  For example you may want to display a related record's name, but the related record is now deleted.

Perhaps the feature in #171 needs to stay, and we need a second option to override the display.

**Comment by ilgiz-badamshin** [comment]
What about to improve #171 and add 'saveField' property. We can set it as pseudo field 'country.name'. AuditTrailBehavior save origin country_id and country.name fields. In auditTrailPanel we can see two diffs for country_id and 'country.name'.
Version::getVersion will be restores only $model->attributes() and pseudo field 'country.name' will be ignored. If 'saveField' is not set, then all will be work as now.

**Comment by cornernote** [comment]
Hi @ilgiz-badamshin,

Sounds like it could work.  Are you able to do a PR for this so I can have a look/play?

**Comment by ilgiz-badamshin** [comment]
Yes. #182
