### ISSUE TITLE
Ability to use custom user id instead Yii::$app->user->id

### ISSUE THREAD

**Issue by ilgiz-badamshin** [bedezign/yii2-audit#174]
I use yii2 advanced template and i have BackendUser and FrontendUser. 
I created AuditUser that contains id, backend_user_id, frontend_user_id . 
Now i want  save AuditUser.Id in AuditEntry instead Yii::$app->user->id. 
How can i do it?
userIdentifierCallback and userFilterCallback used for display and filter by AuditUser model.

**Comment by cornernote** [comment]
I believe there is no current feature that will allow this.  Yii2-Audit will just save the user_id as defined by the Yii2 application (`Yii::$app->user->id`).

You can override the userIdentity config as described here:
http://www.yiiframework.com/doc-2.0/guide-security-authentication.html

**Comment by ilgiz-badamshin** [comment]
I already override user identity and i have BackendUser and FrontendUser, that saved in different tables.
I want use one audit for backend and frontend applications, but different users from backend and frontend have same id, so i created AuditUser with unique id for frontend and backend. Can you provide functional to override user_id to save? Like userIdentifierCallback to display custom username.

**Comment by cornernote** [comment]
The code you are writing looks like a good solution.  Once you are done send a PR and I'll take a look.

**Comment by ilgiz-badamshin** [comment]
PR already created #176
