### ISSUE TITLE
Configurable table names

### ISSUE THREAD

**Issue by ilgiz-badamshin** [bedezign/yii2-audit#175]
I use yii2 advanced template and i want use different audit tables for frontend and for backend.

**Comment by cornernote** [comment]
The only way to do this currently is to use a prefix in your db config:

frontend config:
```php
'db'=>array(
  'connectionString' => 'xxxxx',
  'username' => 'xxxxx',
  'password' => 'xxxxx',
  'tablePrefix' => 'fe_',
),
```

backend config:
```php
'db'=>array(
  'connectionString' => 'xxxxx',
  'username' => 'xxxxx',
  'password' => 'xxxxx',
  'tablePrefix' => 'be_',
),
```

Although after thinking about your use-case, that's probably not an option.

At this point I don't have time to create a `tableMap` option, but if you want to have a go, then feel free to send a PR.

**Comment by cornernote** [comment]
Actually, you can do this:

frontend config:
```php
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
        'db' => 'dbAudit',
    ],
    'components' => [
        'dbAudit'=>[
            'connectionString' => 'xxxxx',
            'username' => 'xxxxx',
            'password' => 'xxxxx',
            'tablePrefix' => 'fe_',
        ],
    ],
```

backend config:
```php
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
        'db' => 'dbAudit',
    ],
    'components' => [
        'dbAudit'=>[
            'connectionString' => 'xxxxx',
            'username' => 'xxxxx',
            'password' => 'xxxxx',
            'tablePrefix' => 'be_',
        ],
    ],
```

This way your main `db` component is unaffected.

**Comment by lacek** [comment]
> Actually, you can do this:
> 
> frontend config:
> 
> ```
>     'modules' => [
>         'audit' => 'bedezign\yii2\audit\Audit',
>         'db' => 'dbAudit',
>     ],
>     'components' => [
>         'dbAudit'=>[
>             'connectionString' => 'xxxxx',
>             'username' => 'xxxxx',
>             'password' => 'xxxxx',
>             'tablePrefix' => 'fe_',
>         ],
>     ],
> ```
> 
> backend config:
> 
> ```
>     'modules' => [
>         'audit' => 'bedezign\yii2\audit\Audit',
>         'db' => 'dbAudit',
>     ],
>     'components' => [
>         'dbAudit'=>[
>             'connectionString' => 'xxxxx',
>             'username' => 'xxxxx',
>             'password' => 'xxxxx',
>             'tablePrefix' => 'be_',
>         ],
>     ],
> ```
> 
> This way your main `db` component is unaffected.

This won't work because of

1. duplicate foreign key in yii2-audit's migrations
2. console app of Yii 2 Advanced Template migrates database with the default connection in `db` component.

1 can be resolved by updates to source code in yii2-audit. All foreign key constraint names in the migrations should be properly quoted with Yii'2 convention to support table prefix. E.g. for 
https://github.com/bedezign/yii2-audit/blob/master/src/migrations/m150626_000002_create_audit_data.php#L22, we can have:

```diff
-            $this->addForeignKey('fk_audit_data_entry_id', self::TABLE, ['entry_id'], '{{%audit_entry}}', 'id');
+            $this->addForeignKey('{{%fk_audit_data_entry_id}}', self::TABLE, ['entry_id'], '{{%audit_entry}}', 'id');
```

2 can be resolved be rearranging the configs a bit, e.g.:

common config:

```php
    'components' => [
        'dbFrontendAudit'=>[
            'connectionString' => 'xxxxx',
            'username' => 'xxxxx',
            'password' => 'xxxxx',
            'tablePrefix' => 'fe_',
        ],
        'dbBackendAudit'=>[
            'connectionString' => 'xxxxx',
            'username' => 'xxxxx',
            'password' => 'xxxxx',
            'tablePrefix' => 'be_',
        ],
    ],
```

frontend config:

```php
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
        'db' => 'dbAudit',
    ],
```

backend config:

```php
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
        'db' => 'dbAudit',
    ],
```

console config:

```php
    'controllerMap' => [
        'migrate-frontend' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationPath' => [
                '@frontend/migrations', // required to ensure the migrate-frontend command doesn't run migrations in console app, the folder doesn't need to exist if no frontend specific migration is needed
            ],
            'migrationNamespaces' => [
                'bedezign\yii2\audit\migrations',
            ],
            'migrationTable' => 'migration_frontend',
            'db' => 'dbFrontendAudit',
        ],
        'migrate-backend' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationPath' => [
                '@backend/migrations',
            ],
            'migrationNamespaces' => [
                'bedezign\yii2\audit\migrations',
            ],
            'migrationTable' => 'migration_backend',
            'db' => 'dbBackendAudit',
        ],
    ],
```

In this way, you should then be able to create required tables by the separate migrate commands:

```sh
# run frontend migrations, including frontend audit tables
./yii migrate-frontend

# run backend migrations, including backend audit tables
./yii migrate-backend

# run common migrations
./yii migrate
```
