### ISSUE TITLE
Conflict with yii-debug 2.0.7

### ISSUE THREAD

**Issue by schmunk42** [bedezign/yii2-audit#177]
I know that this is fixed on master, but I'd still open an issue for this, details: https://github.com/yiisoft/yii2-debug/issues/169

You could add a `"conflict"` to composer.json in a commit right after (or branched from) your 1.0.7.

If you release a new version, I'd recommend a 1.1.0 - if the above change has to be included.

**Comment by Blizzke** [comment]
Guess we can consider this one atrophied :)
