### ISSUE TITLE
Changes are not auditted when updateAttributes() is used.

### ISSUE THREAD

**Issue by thyseus** [bedezign/yii2-audit#183]
Currently, changes are not saved inside the audit trail when attaching bedezign\yii2\audit\AuditTrailBehavior onto an model and calling updateAttributes(), for example:

```php
class Stuff extends ActiveRecord {
 public function behaviors()
    {
        return [
            'bedezign\yii2\audit\AuditTrailBehavior',
        ];
  }
}
```

```php
$model = Stuff::findOne(1);
$model->updateAttributes(['name' => 'new_name']);
```

The change is not being registered. 

There is no event in the yii2 core to attach this to easily.

Any ideas on how to solve this problem?

**Comment by cornernote** [comment]
There are several methods that have this same issue: `updateAll`, `deleteAll`, etc.

`updateAttributes` is basically a wrapper around `updateAll`.  There's not a lot that can be done.  Try to avoid using `updateAttributes` and similar functions.

I'll leave this issue open incase anyone has better ideas.

**Comment by thyseus** [comment]
My idea is to open an Pull Request at the yii framework core that ensures that either

a) EVENT_BEFORE_UPDATE and EVENT_AFTER_UPDATE gets triggered on all update...() variants or
b) we introduce an EVENT_BEFORE_UPDATEATTRIBUTE and EVENT_AFTER_UPDATEATTRIBUTE event.

**Comment by thyseus** [comment]
Proposal on how one could do it is submitted to the yii2 core: https://github.com/yiisoft/yii2/pull/13375

**Comment by thyseus** [comment]
I close this issue since the issue won´t be 'fixed' in the yii2 core.
