### ISSUE TITLE
audit_mail table `data too long`

### ISSUE THREAD

**Issue by Quexer69** [bedezign/yii2-audit#187]
`Data too long for column 'data' at row 1`

When sending Emails with attachments larger than 64 KB

`A BLOB column with a maximum length of 16,777,215 (224 − 1) bytes`

You will get this error:

![audit_mail_error](https://cloud.githubusercontent.com/assets/3859353/22198202/c0a1b0fa-e155-11e6-9c18-f3a4a6c3d574.png)

I would suggest adding an option to exclude the attachment from mail body `toString()` in https://github.com/bedezign/yii2-audit/blob/master/src/panels/MailPanel.php#L80

An other option could be to update the `audit_mail` table data column to a `MEDIUM_BLOB`. But I think this will inflate this table to much!?

What do you think ?

CC: @schmunk42

**Comment by Blizzke** [comment]
As far as I know we are [not storing attachments at this point at all](https://github.com/bedezign/yii2-audit/blob/master/src/panels/MailPanel.php#L68). 

Increasing the field size to either medium- or longblob will add 1 or 2 bytes per record respectively as compared to storage now, so that might be an option. You could also just do this yourself with an `ALTER TABLE`-statement in a later migration without having to wait for an update from our end. You will not lose data by making the field bigger.

**Comment by Quexer69** [comment]
It seems that you are right, but after `$mail->data = $message->toString();` in [MailPanel.php#L80](https://github.com/bedezign/yii2-audit/blob/master/src/panels/MailPanel.php#L80) the full attachment is in that string.

**Trace:**

1. `\yii\swiftmailer\Message->toString()`
2. `Swift_Message->toString()`
3. `Swift_Mime_SimpleMessage->toString()`

**Comment by schmunk42** [comment]
We need to be careful when adding so much data to the database. It should not be a default. 

I was talking with  @cornernote about similar issues concerning logging logs, database & profile.

Related https://github.com/bedezign/yii2-audit/pull/186

**Comment by Blizzke** [comment]
> but after $mail->data = $message->toString(); in MailPanel.php#L80 the full attachment is in that string.

Right, now that you mention it... IIRC the idea was to keep some data for quick displaying but also to  the rest of the message as well if the user wanted to see it again (it's been a while).

Problem with most of the panels is that everyone has different needs. While you might not need the attachments, someone else might not even need the content, or any other of the fields.

Idea here might be to provide add a list of mail properties we (can) save to the panel configuration and allow a user to modify it to his needs. 
Pretty sure that if we just add support for "not storing the mail as data", the next question will be to allow the same for the body :)

**Comment by Quexer69** [comment]
> Problem with most of the panels is that everyone has different needs and that it is hard to please them all. While you might not need the attachments, someone else might not even need the content, or any other of the fields.

You are right, but the fact that the `data` column in `audit_mail` table ist just a BLOB type is limiting everyone who is logging is email traffic. A long HTML email wont fit into this column and causes the mentioned error. Never mind emails with attachments.

So therefore I would suggest:

1. Alter the `data`column from `BLOB` to `LONGBLOB`
2. Introduce a public property `storeData` default to `false` to the `bedezign\yii2\audit\panels\MailPanel`. Your panel interface is already prepared for that ;)

The config would look like:

```
$config = [
    'modules' => [
       'audit' => [
          'panels' => [
             'audit/mail' => [
                 'storeData' => false|true,
             ]
          ],
       ],
    ],
]
```

What do you think ?

**Comment by Blizzke** [comment]
Wasn't arguing about the size of the column, I agree :)

I would just prefer to introduce some more generic solution for including excluding specific data, ie 
```
$config = [
    'modules' => [
       'audit' => [
          'panels' => [
             'audit/mail' => [
                // Store everything except for 'data' and 'html'
                 'exclude' => ['data', 'html'],
                 // Or: store only 'to' and 'from'
                'include' => ['to', 'from']
             ]
          ],
       ],
    ],
]
```

Like that it could also be applied to most of the other models, assuming the related attributes either accept `null` or have a default value. For displaying we'd have to modify for the possibility that columns could be empty (either not show them depending on the config or show them with an "empty value") 

It would be some work, but might be worth it... @cornernote what do you think?
