### ISSUE TITLE
PHP Strict Warning – yii\base\ErrorException Declaration of bedezign\yii2\audit\components\panels\DataStoragePanelTrait::getUrl() should be compatible with yii\debug\Panel::getUrl($additionalParams = NULL)

### ISSUE THREAD

**Issue by lowap** [bedezign/yii2-audit#192]
Hi,

I've installed wampserver 3.0.6 + yii2 basic template on friday, audit today (both with composer), and after setting config/modules up I 'm getting this error message. Can you please point me to the right direction?
Thanks a lot!
BR

**Comment by luiseduardo** [comment]
Same issue with me.

**Comment by cornernote** [comment]
This relates to #172

It appears the Yii2 basic template is using an older version of Yii2 debug.

Try using yii2-audit 1.0.7 for the time being.

**Comment by lowap** [comment]
1.0.8 helped, thx a lot! Really nice extension!
