### ISSUE TITLE
AuditTrialBehavior is not working when extend to the model and using it in other models.

### ISSUE THREAD

**Issue by a3aakash** [bedezign/yii2-audit#196]
use bedezign\yii2\audit\models\AuditTrail;

/* This is my custom model which is extending active record class */
class Callback extends \yii\db\ActiveRecord {
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'bedezign\yii2\audit\AuditTrailBehavior'
        ];
    }
}

/* And this class is being extended by other models */
class Post extends Callback {
    public static function tableName() {
        return 'posts';
    }
}

@bedezign this scenario is not working on my application. Please help me out. Is it a bug, something I am missing or misinterpreting your module. 
thank you.

**Comment by cornernote** [comment]
Can you try another behavior, like timestamp or something, just to see if
that works.

**Comment by cornernote** [comment]
Also, is trail working if you put it into your Post model directly?

**Comment by a3aakash** [comment]
@cornernote yes trail is working, if we extend directly to Active record with post model.

Also i m new to yii2 and implemented your plugin into the project for audit logs so I dont know how to use your module with timestamp behavior. 

Also I got one more issue that when a form had 50 fields in it then trail are entering all 50 records as separate record which will slowdown the database process if multiple users checked in.

**Comment by cornernote** [comment]
I'll try to get time to test this tomorrow.

Please create a new issue for your other question as it requires
explanation about the architecture of the module

**Comment by a3aakash** [comment]
Okay please let me know with this as I have to implement it asap.

**Comment by cornernote** [comment]
Seems to work for me... I did the following...

1) install yii2-basic and yii2-audit-module

2) setup models:

`app/models/ActiveRecord.php`

```php
<?php
namespace app\models;
use bedezign\yii2\audit\AuditTrailBehavior;
class ActiveRecord extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            AuditTrailBehavior::className(),
        ];
    }
}
```

`app/models/Post.php`

```php
<?php
namespace app\models;
class Post extends ActiveRecord
{
}
```

Then I setup a controller to save a row...

`app/controllers/TestController.php`

```php
<?php
namespace app\controllers;
use app\models\Post;
use yii\web\Controller;
class TestController extends Controller
{
    public function actionIndex()
    {
        $post = new Post;
        $post->title = 'test';
        $post->body = 'test';
        $post->save();
    }
}
```

Then run it via `http://localhost/index.php?r=test`.

I look in the `audit_trail` table and there are rows.  Everything seems to work as expected.
