### ISSUE TITLE
Form with more than 100 fields.

### ISSUE THREAD

**Issue by a3aakash** [bedezign/yii2-audit#198]
I got one issue that when a form had 100 fields in it, then trail are entering all 100 records as separate record which will slowdown the database process if multiple users checked in. I suppose it should make one record and bind all the fields into one column. If there is any component please let me know.

**Comment by cornernote** [comment]
It does an insert SQL like this:

```
INSERT INTO `audit_trail` (`model`,`model_id`,`field`,`old_value`,`new_value`)
VALUES ('Post','1','id','','1'), ('Post','1','title','','test'), ('Post','1','body','','test')
```

Because of this, it's only running a single query each time a model is saved, regardless of the number of fields.  It does insert many records into the table, but this is a requirement of the module, it needs to be able to find all the changes to a specific field.

**Comment by a3aakash** [comment]
I understand the functionality you have done. But my issue is that I have multiple fields which is to form single data-set, for example, my query will be like:

```
INSERT INTO `audit_trail` (`model`,`model_id`,`old_values`,`new_values`)
VALUES ('Post','1','','{"id":"1","title":"test","body":"test", .......}')
```

Note: I have removed the field column and revised the old_value &new_value columns to old_values & new_values to make a single data-set for an HTML form.

If there is any feature which offers this from your end, we are highly appreciated.

**Comment by cornernote** [comment]
Unfortunately the AuditTrail doesn't save data like this.

You would have to make a new behavior and a new panel (or extend trail and change it to suit).

**Comment by a3aakash** [comment]
ok nice suggestion.
