### ISSUE TITLE
Audit::getInstance() always return null, if I register the config file, Undefined class constant 'yii\debug\Module::DEFAULT_IDE_TRACELINE'

### ISSUE THREAD

**Issue by hkkhchan** [bedezign/yii2-audit#202]
in the AuditTrailBehaviour.php
Audit::getInstance() always return null.

if I register the config file.
`        'audit' => [
             'class' => 'bedezign\yii2\audit\Audit',
		]`

Error message exist as 
Undefined class constant 'yii\debug\Module::DEFAULT_IDE_TRACELINE'

**Comment by cornernote** [comment]
Are you using the latest release?

**Comment by hkkhchan** [comment]
I am using the latest because the composer.json show
"bedezign/yii2-audit" : "^1.0"
"yiisoft/yii2-debug" : "*"

composer.phar show
yiisoft/yii2-debug 2.0.6
bedezign/yii2-audit: 1.0.10

Now I hard code an integer to the Audit.php and now it is ok. but I am not sure how is the impact.

`    //public $traceLine = \yii\debug\Module::DEFAULT_IDE_TRACELINE;
	public $traceLine = 1;`

**Comment by cornernote** [comment]
You're getting an old yii2-debug for some reason
