### ISSUE TITLE
No panels data

### ISSUE THREAD

**Issue by atakajlo** [bedezign/yii2-audit#206]
If I enabled some parsers in my config

```php
'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
            'baseUrl' => '/admin',
            'parsers' => [
                 'application/json' => 'yii\web\JsonParser',
            ],
        ],
]
```

I get this (no panels data)
![image](https://cloud.githubusercontent.com/assets/5870060/26726203/e00b569c-47aa-11e7-911c-31bd789ffae0.png)

Could you help me?

**Comment by cornernote** [comment]
Audit panels extend from yii2 debug panels. Does yii2 debug capture the
details?

**Comment by atakajlo** [comment]
@cornernote no. maybe you can explain me why this happens with enabled parsers?

**Comment by cornernote** [comment]
You would have more luck getting an explanation from the yii2-debug
project.  I'm not sure why it's the case, all I can tell you is that if
it's not working in yii2-debug then it won't work in yii2-audit.

**Comment by atakajlo** [comment]
okay. thank you
