### ISSUE TITLE
/audit/entry panel gets timed out when trails panel has more than 1 million items

### ISSUE THREAD

**Issue by cyberinferno** [bedezign/yii2-audit#214]
Possible problem: Entry panel join with trail table causes performance bottle neck

My temporary solution: I commented out 'trail' column in index file of entry controller and page loaded as usual

**Comment by Blizzke** [comment]
We just had a PR merged that should help you out there, courtesy of @shalvah. 
It greatly reduces the number of queries executed for the main screen.
I'll draft up a new release asap. Hopefully that solves your issues.

**Comment by cyberinferno** [comment]
There seems to be a problem while updating to latest version as you added some `php-mime-mail-parser` as dependancy which I am not able to rectify in PHP7.0.

**Comment by cornernote** [comment]
I think it will need to be made optional then, as it is used to display
embedded attachments in html emails.

I'm not quite sure how to make a dependency optional, and don't have time
to research right now.  Can look, but might not be for a couple of weeks.


-- Brett

**Comment by Blizzke** [comment]
I know this is extremely late, but I've removed the mailparser as a required extension. I'm going to assume that this was the only thing stopping you to use the new version and will close this. Feel free to re-open if not.
