### ISSUE TITLE
forbidden 403 error

### ISSUE THREAD

**Issue by peanhuang** [bedezign/yii2-audit#227]
I install and config my project by following the document, but I come across the forbidden 403 error when I access the web site by using 

> http://localhost/path/to/index.php?r=audit

. Finally I figure it out that you have to change the following config a little bit:
```
<?php
$config = [
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
    ],
];
```
to 
```
<?php
$config = [
    'modules' => [
        'audit' => 'bedezign\yii2\audit\Audit',
        'accessRoles' => null,
    ],
];
```

**Comment by Blizzke** [comment]
That is indeed the intended behavior. By default the audit pages are only accessible for people in the admin role.
