### ISSUE TITLE
Add note about PHP extension mailparse

### ISSUE THREAD

**Issue by schmunk42** [bedezign/yii2-audit#229]
Since [1.0.12](https://github.com/bedezign/yii2-audit/commit/2b125571238ddc1f17fd4172db6f107503f6fed4#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) you need the PHP extension `mailparse`, which is a requirement of `php-mime-mail-parser/php-mime-mail-parser`.

While there's no error when installing `yii2-audit` it might be worth adding a note to the README or UPGRADING, since it might be hard to understand why you do not get updates after `1.0.11`, when you do not have the extension compiled. I'd also suggest to release a `1.1`, since this is a fairly large change in requirements.

**Comment by Blizzke** [comment]
I've made the extension optional. `php-mime-mail-parser` is now a suggestion and the view will detect if the `Parser` is installed. If not it will simply dump the raw mail text. If it is installed, the behavior will be as it was in the last versions.
