### ISSUE TITLE
Object is a reserved keyword in php 7.2

### ISSUE THREAD

**Issue by balrok** [bedezign/yii2-audit#231]
For example `src/components/Helper.php` should not inherit from Object. The yii team renamed it to BaseObject

**Comment by karataserkan** [comment]
We can not use Yii versions <2.0.13 to be compatible with PHP 7.2 or higher. Our composer.json requires `"yiisoft/yii2": "2.*"`.
To compatible with PHP 7.2 or higher, we also update our composer.json. I think we should not do that.
Yii2 Audit sould be compatible with Yii versions <2.0.13

**Comment by balrok** [comment]
Hi,
I forked this project to fix this issue: https://github.com/balrok/yii2-audit
At the bottom of the readme is also how you can add it to the composer.json

**Comment by Blizzke** [comment]
Just wanted to let it be know that it is not because we currently have very little time to fix issues ourselves that we won't merge pull requests and draft new releases for them. 
So feel free to submit a PR for this and we'll take care of it.

**Comment by StalkAlex** [comment]
@balrok  why just not create PR instead of fork?

**Comment by balrok** [comment]
Please do it for me - I never did a pull request.

On the other hand the maintainer could simply:
```
wget https://github.com/balrok/yii2-audit/commit/33b6c4bc27823bd982ab2d5227ee955b95749d00.patch
patch -d . -p1 < 33b6c4bc27823bd982ab2d5227ee955b95749d00.patch
```

**Comment by Blizzke** [comment]
New releases [1.0.13](https://github.com/bedezign/yii2-audit/releases/tag/1.0.13) and [1.1.0](https://github.com/bedezign/yii2-audit/releases/tag/1.1.0) resolve this.
 
**1.0.13** is for PHP < 7.2, it will work for all Yii2 versions
**1.1.0** is for PHP >= 7.2 and requires at least Yii2 2.0.13
