### ISSUE TITLE
Undefined variable: sumDuplicates with yii-debug 2.0.13

### ISSUE THREAD

**Issue by williamyiu** [bedezign/yii2-audit#233]
yii-debug 2.0.13 added query duplicate on 2.0.13. See the following

https://github.com/yiisoft/yii2-debug/commit/e74d0937760ba46fecfab198e9596e9574e1fa8e

I think the fix would be added the variable $sumDuplicates at \panels\DbPanel.php

**Comment by Blizzke** [comment]
Thanks for reporting this, this was fixed in release [1.0.13](https://github.com/bedezign/yii2-audit/releases/tag/1.0.13) / [1.1.0](https://github.com/bedezign/yii2-audit/releases/tag/1.1.0)
