### ISSUE TITLE
new option 'language' in Module Configuration

### ISSUE THREAD

**Issue by seraos** [bedezign/yii2-audit#237]
new option 'language' in Module Configuration, to overrride 'language' in web.conf.

'language'=>'en'

2018-01-26 15:52:04
[::1][2][-][error][yii\i18n\PhpMessageSource::loadFallbackMessages]
The message file for category 'audit' does not exist:
/dados/Dropbox/site/saaesgs/vendor/bedezign/yii2-audit/src/messages/pt-BR/audit.php

**Comment by Blizzke** [comment]
Unfortunately we have no control over what messages are loaded, so fixing that is beyond our control. The translations are handled by the frameworks' translation component.

It depends on your translation configuration. 
I think you are probably missing a value for `sourceLanguage` [in your settings](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#configuration), which would enable it to fall back to english if it cant find the language you want to use.
