### ISSUE TITLE
Db panel extends \yii\debug\panels\DbPanel,But when I dont have connection which named 'db',It will not work.

### ISSUE THREAD

**Issue by Nash-x9** [bedezign/yii2-audit#239]
Db panel extends \yii\debug\panels\DbPanel,But when I dont have connection which named 'db',It will not work.

My config like this:
```php
<?php
return [
    'components' => [
        'read_data'=> [
             'class' => 'yii\db\Connection',
             //some other config
        ],
        'write_data'=> [
             'class' => 'yii\db\Connection',
            //some other config
        ],
    ],
];
```
That I don't have any Connection called 'db'.So it will throw these:
Invalid Configuration – yii\base\InvalidConfigException
Unknown component ID: db

**Comment by Blizzke** [comment]
The debug `DbPanel` assumes that a `db` connection is present. 
Audit's `DbPanel` does nothing in that matter as it just overrides that class's logging functionality. 

So to make this work you'll have to configure the panel with a `db` value that point to the correct connection. 
Basically you can just set the `'db' => 'connection name'` in your audit panel configuration and it will be used. 
The [Module Configuration](https://bedezign.github.io/yii2-audit/docs/module-configuration/) should be able to help you further..
