### ISSUE TITLE
how to cleanup with cron ?

### ISSUE THREAD

**Issue by michaelnguyen547** [bedezign/yii2-audit#243]
I setup a cron job that do cleanup everyday. 

```
0 12 * * * php yii audit/cleanup --age=30
```

The cleanup script requires user input to proceed 

Cleanup the above data? (yes|no) [no]:

How do I do that with cron ?

**Comment by Blizzke** [comment]
audit follows yii guidelines in this matter, you can use the `--interactive=0` option that is available for most commands

**Comment by schmunk42** [comment]
For anyone else stumbling upon this...

There's now:

`yii audit/cleanup --entrySolo`

which cleans up only entries without attached data.
