### ISSUE TITLE
Exist some configuration for don't save information on column "data" from "audit_data" table?

### ISSUE THREAD

**Issue by vicsanjinez** [bedezign/yii2-audit#248]
this column is growing my database, usually the backup is 70Mb per day, since the library installs the backup grows every day at 150Mb, there is some way to not save data in the column "data" of the table "audit_data"?

Statistics of tables of audit library ( size of "audit_data" is 530Mb, size of "audit_trail" is 5Mb)

https://i.stack.imgur.com/yl1RS.png

**Comment by Blizzke** [comment]
`audit_data` basically contains all data related to the requests. 
What is stored in there depends on [the panels](https://github.com/bedezign/yii2-audit#log-data-using-configurable-panels) you have enabled. 
If you want less information stored per request, see what you can miss, disable that panel in your configuration and just delete all entries from that table by its `type`. Some panels support "partial disabling", like the Request panel for example, where you can configure the keys it should ignore.

**Comment by vicsanjinez** [comment]
Ok thanks @Blizzke  for th answer!
