### ISSUE TITLE
Audit cannot be extended due to usage of Audit::getInstance()

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#251]
If you try to do something like this in your config array, all hell breaks loose:

```
  'modules' => [
        'audit' => [
            //'class' => 'bedezign\yii2\audit\Audit',
            'class' => 'app\components\audit\Audit', 
        ],
    ],
```

The reason is because `Audit::getInstance()` uses the calling class's name.

**Comment by Blizzke** [comment]
`getInstance` method was overridden to allow exactly this.
