### ISSUE TITLE
'ignoreActions' => ['audit/*', 'debug/*']

### ISSUE THREAD

**Issue by neoacevedo** [bedezign/yii2-audit#256]
Shouldn't `'ignoreActions' => ['audit/*', 'debug/*']` avoid write into audit_data table these routes?
Plus, related to #138 with `'ignoreActions' => ['*'],` all is recorded in audit_entry table so _ignoreActions_ still is buggy.

**Comment by neoacevedo** [comment]
`'ignoreActions' => ['audit/*', 'debug/*', '*/index'],`:

![screenshot_20190110_135453](https://user-images.githubusercontent.com/438372/50990363-d4aed180-14df-11e9-9d6c-50483aa63d18.png)

**Comment by Blizzke** [comment]
It's weird. I ran it on a test project with just the ignoreActions defined like you specified them, and it's nicely ignoring the `site/index` views (that's what I tested), as it should. Is there something else configured or do you something with the `$uniqueId` of Yii's `ActionEvent`?

**Comment by neoacevedo** [comment]
It's a clear yii2 app, although good, I'm using the advanced app and I have set this in backend's config for RBAC:
```php
'as access' => [
    'class' => backend\filters\AccessControl::class,
    'allowActions' => ['site/login', 'site/logout', 'site/error', 'debug', 'gii']
]
```

**Comment by borraz** [comment]
I have a similar problem:
```
'ignoreActions' => ['audit/*', 'debug/*', 'certificate/*'],
```
![image](https://user-images.githubusercontent.com/9478141/55400387-0d45d080-554e-11e9-83b9-6da2b4e6009b.png)

When the request_method is not GET the ignoreActions dont work as expected.

**Comment by marty-macfly** [comment]
Hello,

I've reproduce the same issue and it seems to be related to the error handler `\bedezign\yii2\audit\components\web\ErrorHandler` creating the audit entry and not the Audit->onBeforeAction method that use the `ignoreActions` filter.

If I'm disabling error handler I don't have the audit entry anymore. Here is the stack trace I can see:

```
/app/vendor/lbn/yii2-config/src/db/mysql/Command.php:25
/app/vendor/lbn/yii2-config/src/db/mysql/Command.php:60
/app/vendor/bedezign/yii2-audit/src/models/AuditEntry.php:166
/app/vendor/bedezign/yii2-audit/src/models/AuditEntry.php:55
/app/vendor/bedezign/yii2-audit/src/Audit.php:321
/app/vendor/bedezign/yii2-audit/src/components/base/ErrorHandlerTrait.php:38
```

**Comment by Blizzke** [comment]
Okay, got it.
Errors by default are always logged as it is assumed that that is exactly the information you want.
I can however see that you might not want specific entries so I'll see if I can add a second set of tracking-filters for error specifically.

**Comment by Blizzke** [comment]
1.1.2 has 2 new variables: `$trackErrorActions` and `$ignoreErrorActions`. They work the same as the regular ones but for errors. Please note that due to how Yii works (logException functionality) there's no consistent `ActionEvent` instance to verify (to obtain the route). To get around that, the error handler uses `Yii::$app->requestedRoute`
