### ISSUE TITLE
Hii.. im using this extension and im using bootstrap 4

### ISSUE THREAD

**Issue by taroom** [bedezign/yii2-audit#268]
yii\bootstrap\BootstrapAsset is causing error 

Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "yii\bootstrap\BootstrapAsset".

**Comment by Blizzke** [comment]
I've made some changes to get this to work in 1.1.2
It should be able to auto detect whether you use the "old" bootstrap or bootstrap4.
Let me know if any problems occur.
