### ISSUE TITLE
check if a user has permission to access link

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#27]
In the 2 partials I created:
https://github.com/bedezign/yii2-audit/blob/master/views/_audit_entry_id.php
https://github.com/bedezign/yii2-audit/blob/master/views/_audit_trails.php

I would like to be able to render a link to the audit view page, but only if the user has access.  Do you know how I can check this?

**Comment by Blizzke** [comment]
There is a trait that you can add to a controller that defines an `AccessControl`-filter with the correct permissions. If you have a dedicated controller for those auditing actions you should be set with just doing `use \bedezign\yii2\audit\components\ControllerTrait;` in there. Is that what you were looking for?

**Comment by cornernote** [comment]
Not really.  Say I have a view in my application, I want to do like this:

```php
$someCondition = '???'; // check if user has access to audit module
if ($someCondition) {
  echo $auditEntry->id;
} else {
  echo Html::a($auditEntry->id, ['/auditing/default/view', 'id' => $auditEntry->id]);
}
```

**Comment by Blizzke** [comment]
Hmm I see. There is no real functionality in that area at the moment, but I guess it could be added in the module... `\Yii::$app->auditing->checkAccess()` or something. I'll look into it.

**Comment by Blizzke** [comment]
`if (\Yii::$app->auditing->checkAccess()) ....`
