### ISSUE TITLE
Namespaced migrations cause error

### ISSUE THREAD

**Issue by schmunk42** [bedezign/yii2-audit#271]
@Blizzke @cornernote https://github.com/bedezign/yii2-audit/pull/267 is a BC-breaking change, because you need to run this in new projects, but exclude it in existing ones. Which is pretty hard to accomplish.

I think there should be a check if the un-namespaced migations have been run - and actually also mark them.

Or do I miss another solution?

CC: @eluhr @handcode

**Comment by Blizzke** [comment]
Hmm good point. I guess the only thing we can do is see if there's a way that every migration can figure out if it was ran un-namespaced and then do nothing so it just gets marked as executed. I'll see if I can figure something out but it won't be the first week or 2, unfortunately dealing with personal matters atm.

**Comment by schmunk42** [comment]
Was there a special reason for you to change it?

btw: There was a lengthy discussion about it: https://github.com/yiisoft/yii2/issues/13356

**Comment by Blizzke** [comment]
It was requested, looked at the docs and got the impression that that's what they wanted as default behavior. So I changed it.

**Comment by schmunk42** [comment]
IMHO there's no reason why it should be required.

What do you think about reverting it?

A change like this would actually require a new major version (semver)

**Comment by schmunk42** [comment]
Fixed in 1.2.6, see also https://github.com/bedezign/yii2-audit?tab=readme-ov-file#yii2-audit-12x
