### ISSUE TITLE
The css of the view pages are broken .Header menu is invisible .  

### ISSUE THREAD

**Issue by vrindhasajikumar** [bedezign/yii2-audit#272]

**Comment by Blizzke** [comment]
I'm sorry, there's little I can do with this..."ticket".. with so little information
There's a lot of people using this and you're the first to have this problem. Perhaps check if you correctly registered the assets? 
Going to close this, feel free to open another ticket with some more information and actual content.

**Comment by vrindhasajikumar** [comment]
Hi,
All the CSS included correctly but the menu is invisible , and other styles are broken . Image is attached in this note.When I remove the colllapse class in the menu it will show otherwise invisible .Please help me to solve these design Issues.

![audit_trail](https://user-images.githubusercontent.com/59190181/71569083-816bcf80-2af2-11ea-8cf1-d466f5ea8ce3.png)
