### ISSUE TITLE
Trying to get property 'uniqueId' of non-object in Audit.php on line 248

### ISSUE THREAD

**Issue by ashaduri** [bedezign/yii2-audit#274]
Hi,

I get this error when running:
`$ ./yii migrate/create`

> PHP Notice:  Trying to get property 'uniqueId' of non-object in vendor/bedezign/yii2-audit/src/Audit.php on line 248
> PHP Stack trace:
> PHP   1. bedezign\yii2\audit\components\console\ErrorHandler->handleException($exception = class yii\console\Exception { protected $message = 'Missing required arguments: name'; private ${Exception}string = ''; protected $code = 0; protected $file = 'vendor/yiisoft/yii2/console/Controller.php'; protected $line = 202; private ${Exception}trace = array (0 => array (...), 1 => array (...), 2 => array (...), 3 => array (...), 4 => array (...), 5 => array (...), 6 => array (...), 7 => array (...)); private ${Exception}previous = NULL; public $xdebug_message = '\nyii\\console\\Exception: Missing required arguments: name in vendor/yiisoft/yii2/console/Controller.php on line 202\n\nCall Stack:\n    0.0001     405848   1. {main}() yii:0\n    0.0192    4716656   2. yii\\console\\Application->run() yii:28\n    0.0194    4889936   3. yii\\c...' }) vendor/yiisoft/yii2/base/ErrorHandler.php:0
> PHP   2. bedezign\yii2\audit\components\console\ErrorHandler->logException($exception = class yii\console\Exception { protected $message = 'Missing required arguments: name'; private ${Exception}string = ''; protected $code = 0; protected $file = 'vendor/yiisoft/yii2/console/Controller.php'; protected $line = 202; private ${Exception}trace = array (0 => array (...), 1 => array (...), 2 => array (...), 3 => array (...), 4 => array (...), 5 => array (...), 6 => array (...), 7 => array (...)); private ${Exception}previous = NULL; public $xdebug_message = '\nyii\\console\\Exception: Missing required arguments: name in vendor/yiisoft/yii2/console/Controller.php on line 202\n\nCall Stack:\n    0.0001     405848   1. {main}() yii:0\n    0.0192    4716656   2. yii\\console\\Application->run() yii:28\n    0.0194    4889936   3. yii\\c...' }) vendor/yiisoft/yii2/base/ErrorHandler.php:119
> PHP   3. bedezign\yii2\audit\Audit->shouldTrack($event = class stdClass { public $action = array ('uniqueId' => 'migrate/create') }, $isError = TRUE) vendor/bedezign/yii2-audit/src/components/base/ErrorHandlerTrait.php:39
> Error: Missing required arguments: name
> 

The offending line in Audit.php is:
`if (!empty($trackActions) && !$this->routeMatches($event->action->uniqueId, $trackActions))`

The stack trace shows that the variable $event is created in ErrorHandlerTrait::logException():
`$event = (object) ['action' => ['uniqueId' => Yii::$app->requestedRoute]];`

The debugger shows that `uniqueId` is a key in array, not a member of an object, which is causing this notice.

My PHP is 7.2.5 (running on Linux).
Composer info:
> 2amigos/yii2-chartjs-widget          2.1.3              ChartJs widget for Yii2.
> amnah/yii2-user                      5.0.9              Yii 2 user authentication module
> beaten-sect0r/yii2-db-manager        2.2.2              The db dump manager module for Yii2
> bedezign/yii2-audit                  1.1.2              Yii2 Audit records and displays web/cli...
> behat/gherkin                        v4.6.1             Gherkin DSL parser for PHP 5.3
> bower-asset/bootstrap                v3.4.1            
> bower-asset/chartjs                  v2.9.3            
> bower-asset/inputmask                3.3.11            
> bower-asset/jquery                   3.4.1             
> bower-asset/moment                   2.24.0            
> bower-asset/punycode                 v1.3.2            
> bower-asset/yii2-pjax                2.0.7.1           
> cebe/markdown                        1.2.1              A super fast, highly extensible markdow...
> codeception/codeception              4.1.1              BDD-style testing framework
> codeception/lib-asserts              1.11.0             Assertion methods used by Codeception c...
> codeception/lib-innerbrowser         1.3.1              Parent library for all Codeception fram...
> codeception/module-asserts           1.1.1              Codeception module containing various a...
> codeception/module-filesystem        1.0.2              Codeception module for testing local fi...
> codeception/module-rest              1.2.0              REST module for Codeception
> codeception/module-yii2              1.1.0              Codeception module for Yii2 framework
> codeception/phpunit-wrapper          8.1.1              PHPUnit classes used by Codeception
> codeception/specify                  0.4.6              BDD code blocks for PHPUnit and Codecep...
> codeception/stub                     3.6.1              Flexible Stub wrapper for PHPUnit's Moc...
> codeception/verify                   1.1.0              BDD assertion library for PHPUnit
> codemix/yii2-configloader            0.10.0             Build configuration arrays from config ...
> conquer/momentjs                     1.0.2              Yii2 momentjs widget
> creocoder/yii2-flysystem             0.9.4              The flysystem extension for the Yii fra...
> doctrine/instantiator                1.3.0              A small, lightweight utility to instant...
> doctrine/lexer                       1.2.0              PHP Doctrine Lexer parser library that ...
> egulias/email-validator              2.1.17             A library for validating emails against...
> elisdn/yii2-gii-fixture-generator    1.1.4              Fixture class generator for Gii module ...
> eusonlito/disposable-email-validator 0.1.9              A PHP package to detect disposable emai...
> ezyang/htmlpurifier                  v4.12.0            Standards compliant HTML filter written...
> fgribreau/mailchecker                dev-master 103123d Temporary (disposable/throwaway) email ...
> flow/jsonpath                        0.5.0              JSONPath implementation for parsing, se...
> fzaninotto/faker                     v1.9.1             Faker is a PHP library that generates f...
> guzzlehttp/psr7                      1.6.1              PSR-7 message implementation that also ...
> himiklab/yii2-recaptcha-widget       2.1.1              Yii2 Google reCAPTCHA v2 and v3 widget
> ivolo/disposable-email-domains       dev-master 6c834c2 disposable domains list
> justinrainbow/json-schema            5.2.9              A library to validate a json schema.
> kartik-v/yii2-dialog                 v1.0.5             An asset bundle for bootstrap3-dialog f...
> kartik-v/yii2-dynagrid               v1.5.1             Turbo charge the Yii 2 GridView with pe...
> kartik-v/yii2-export                 v1.4.0             A library to export server/db data in v...
> kartik-v/yii2-grid                   v3.3.4             Yii 2 GridView on steroids. Various enh...
> kartik-v/yii2-krajee-base            v2.0.5             Base library and foundation components ...
> kartik-v/yii2-mpdf                   v1.0.5             A Yii2 wrapper component for the mPDF l...
> kartik-v/yii2-sortable               v1.2.2             Create sortable lists and grids using H...
> kartik-v/yii2-widget-activeform      v1.5.8             Enhanced Yii2 active-form and active-fi...
> kartik-v/yii2-widget-datepicker      v1.4.7             Enhanced Yii2 wrapper for the bootstrap...
> kartik-v/yii2-widget-datetimepicker  v1.4.9             Enhanced Yii2 wrapper for the bootstrap...
> kartik-v/yii2-widget-select2         v2.1.7             Enhanced Yii2 wrapper for the Select2 j...
> league/flysystem                     1.0.65             Filesystem abstraction: Many filesystem...
> markbaker/complex                    1.4.7              PHP Class for working with complex numbers
> markbaker/matrix                     1.2.0              PHP Class for working with matrices
> mattketmo/email-checker              dev-master e325d2b Throwaway email detection library
> mpdf/mpdf                            v7.1.9             PHP library generating PDF files from U...
> myclabs/deep-copy                    1.9.5              Create deep copies (clones) of your obj...
> opis/closure                         3.5.1              A library that can be used to serialize...
> paragonie/random_compat              v9.99.99           PHP 5.x polyfill for random_bytes() and...
> phar-io/manifest                     1.0.3              Component for reading phar.io manifest ...
> phar-io/version                      2.0.1              Library for handling version informatio...
> phpdocumentor/reflection-common      2.0.0              Common reflection classes used by phpdo...
> phpdocumentor/reflection-docblock    5.1.0              With this component, a library can prov...
> phpdocumentor/type-resolver          1.1.0              A PSR-5 based resolver of Class names, ...
> phpoffice/phpspreadsheet             1.11.0             PHPSpreadsheet - Read, Create and Write...
> phpspec/php-diff                     v1.1.0             A comprehensive library for generating ...
> phpspec/prophecy                     v1.10.3            Highly opinionated mocking framework fo...
> phpunit/php-code-coverage            7.0.10             Library that provides collection, proce...
> phpunit/php-file-iterator            2.0.2              FilterIterator implementation that filt...
> phpunit/php-text-template            1.2.1              Simple template engine.
> phpunit/php-timer                    2.1.2              Utility class for timing
> phpunit/php-token-stream             3.1.1              Wrapper around PHP's tokenizer extension.
> phpunit/phpunit                      8.5.2              The PHP Unit Testing framework.
> psr/container                        1.0.0              Common Container Interface (PHP FIG PSR...
> psr/event-dispatcher                 1.0.0              Standard interfaces for event handling.
> psr/http-message                     1.0.1              Common interface for HTTP messages
> psr/log                              1.1.2              Common interface for logging libraries
> psr/simple-cache                     1.0.1              Common interfaces for simple caching
> ralouphie/getallheaders              3.0.3              A polyfill for getallheaders.
> salaros/is-biz-mail                  0.2.16             isBizMail tells you whether a given ema...
> sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a lin...
> sebastian/comparator                 3.0.2              Provides the functionality to compare P...
> sebastian/diff                       3.0.2              Diff implementation
> sebastian/environment                4.2.3              Provides functionality to handle HHVM/P...
> sebastian/exporter                   3.1.2              Provides the functionality to export PH...
> sebastian/global-state               3.0.0              Snapshotting of global state
> sebastian/object-enumerator          3.0.3              Traverses array structures and object g...
> sebastian/object-reflector           1.1.1              Allows reflection of object attributes,...
> sebastian/recursion-context          3.0.0              Provides functionality to recursively p...
> sebastian/resource-operations        2.0.1              Provides a list of PHP built-in functio...
> sebastian/type                       1.1.3              Collection of value objects that repres...
> sebastian/version                    2.0.1              Library that helps with managing the ve...
> select2/select2                      4.0.13             Select2 is a jQuery based replacement f...
> setasign/fpdi                        1.6.2              FPDI is a collection of PHP classes fac...
> swiftmailer/swiftmailer              v6.2.3             Swiftmailer, free feature-rich PHP mailer
> symfony/browser-kit                  v4.2.4             Symfony BrowserKit Component
> symfony/console                      v5.0.5             Symfony Console Component
> symfony/css-selector                 v5.0.5             Symfony CssSelector Component
> symfony/dom-crawler                  v4.4.5             Symfony DomCrawler Component
> symfony/event-dispatcher             v5.0.5             Symfony EventDispatcher Component
> symfony/event-dispatcher-contracts   v2.0.1             Generic abstractions related to dispatc...
> symfony/finder                       v5.0.5             Symfony Finder Component
> symfony/polyfill-ctype               v1.14.0            Symfony polyfill for ctype functions
> symfony/polyfill-iconv               v1.14.0            Symfony polyfill for the Iconv extension
> symfony/polyfill-intl-idn            v1.14.0            Symfony polyfill for intl's idn_to_asci...
> symfony/polyfill-mbstring            v1.14.0            Symfony polyfill for the Mbstring exten...
> symfony/polyfill-php72               v1.14.0            Symfony polyfill backporting some PHP 7...
> symfony/polyfill-php73               v1.14.0            Symfony polyfill backporting some PHP 7...
> symfony/process                      v4.4.5             Symfony Process Component
> symfony/service-contracts            v2.0.1             Generic abstractions related to writing...
> symfony/yaml                         v5.0.5             Symfony Yaml Component
> theseer/tokenizer                    1.1.3              A small library for converting tokenize...
> vlucas/phpdotenv                     v2.5.2             Loads environment variables from `.env`...
> webmozart/assert                     1.7.0              Assertions to validate method input/out...
> yiisoft/yii2                         2.0.32             Yii PHP Framework Version 2
> yiisoft/yii2-authclient              2.2.7              External authentication via OAuth and O...
> yiisoft/yii2-bootstrap               2.0.10             The Twitter Bootstrap extension for the...
> yiisoft/yii2-composer                2.0.8              The composer plugin for Yii extension i...
> yiisoft/yii2-debug                   2.1.13             The debugger extension for the Yii fram...
> yiisoft/yii2-faker                   2.0.4              Fixture generator. The Faker integratio...
> yiisoft/yii2-gii                     2.1.4              The Gii extension for the Yii framework
> yiisoft/yii2-httpclient              2.0.12             HTTP client extension for the Yii frame...
> yiisoft/yii2-swiftmailer             2.1.2              The SwiftMailer integration for the Yii...
>

**Comment by aagge** [comment]
I am also getting this message.
WAMP
PHP 7.3.4

Works fine in PHP 7.0.10

                            <?php echo \yii2mod\comments\widgets\Comment::widget([
                                        'model' => $model,
                                        'dataProviderConfig' => [
                                              'pagination' => [
                                                  'pageSize' => 5
                                              ],
                                          ]]); ?>    

PHP Notice:  Trying to get property 'uniqueId' of non-object in C:\wamp64\www\ccms\vendor\bedezign\yii2-audit\src\Audit.php on line 248

PHP Notice:  Trying to get property 'uniqueId' of non-object in C:\wamp64\www\ccms\vendor\bedezign\yii2-audit\src\Audit.php on line 248
PHP Stack trace:
PHP   1. bedezign\yii2\audit\components\web\ErrorHandler->handleException() C:\wamp64\www\ccms\vendor\yiisoft\yii2\base\ErrorHandler.php:0
PHP   2. bedezign\yii2\audit\components\web\ErrorHandler->logException() C:\wamp64\www\ccms\vendor\yiisoft\yii2\base\ErrorHandler.php:119
PHP   3. bedezign\yii2\audit\Audit->shouldTrack() C:\wamp64\www\ccms\vendor\bedezign\yii2-audit\src\components\base\ErrorHandlerTrait.php:39
