### ISSUE TITLE
store audit_entry.audit_trail_count

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#29]
in yii1 i used to also store the audit_trail_count in the audit_entry table... then i can delete all records with audit_trail_count=0 after a short period, but retain the data with trails for longer

**Comment by cornernote** [comment]
[3:43:17 PM] Steve G: i was thinking about adding fields for "errors" and "javascript" as well

**Comment by cornernote** [comment]
Yes, and also when we store db profile queries and log/trace data we should add those counts too.

**Comment by Blizzke** [comment]
Might consider an extra counter table so that we can fetch them via relations... seem to become a lot of columns for counters pretty quickly

**Comment by cornernote** [comment]
The problem with that is you need to do a join to get the data.  In my opinion it doesn't matter how many fields you have if it's small data.  Performance will be better if they are in one table.

What are your thoughts?

**Comment by Blizzke** [comment]
Perhaps an alternative solution: 
We keep most important ones (errors, javascript and trail, those which we need in the filter) in the entry table and we add a field to the "data"-table where we store an optional counter per record? Eg  "request_headers", 10

**Comment by cornernote** [comment]
Optional ones can be counted using `count()`, I think there is no need to store that value in the table.

**Comment by cornernote** [comment]
i added the trail count... not sure if we still need it to be a top level field... lets discuss

**Comment by cornernote** [comment]
i'm happy to close this one off, and if we need it later we can come back and do it
