### ISSUE TITLE
Reverting changes

### ISSUE THREAD

**Issue by arogachev** [bedezign/yii2-audit#58]
Like here - https://github.com/airblade/paper_trail#reverting-and-undeleting-a-model

**Comment by cornernote** [comment]
looks like a great idea, can you send through a PR

**Comment by cornernote** [comment]
I haven't tested this at all yet, but it should make for a good starting point:
https://gist.github.com/cornernote/6a6629117b47172b30d1

I considered putting it into the behavior, but then it would be tricky to load for a deleted model.

**Comment by cornernote** [comment]
docs are here: https://github.com/bedezign/yii2-audit/blob/master/docs/database-logging.md#version-control
