### ISSUE TITLE
Move cleanup/truncate functionality to CLI

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#61]
Create a CLI command that takes care of the cleanup of the data. Have it support using a config file to allow specifying different `TTL` values per panel/data type

**Comment by cornernote** [comment]
cleanup command already exists https://github.com/bedezign/yii2-audit/blob/master/src/commands/AuditController.php#L26

But yes, it should support custom TTL values per panel type.

**Comment by cornernote** [comment]
from #61

command example:

```
php yii audit/truncate --panels=audit/error,audit/trail --date=yesterday
```

**Comment by cornernote** [comment]
done, but needs tests

**Comment by cornernote** [comment]
done, added tests for `panel::cleanup()`, but not sure how to test cli commands
