### ISSUE TITLE
PHP Fatal Error – yii\base\ErrorException. Call to a member function getEntry() on a non-object

### ISSUE THREAD

**Issue by cloudswitch** [bedezign/yii2-audit#7]
1. in ...\vendor\bedezign\yii2-audit\AuditingBehavior.php at line 154
$log->audit_id = Auditing::current()->getEntry()->id;

**Comment by Blizzke** [comment]
At this moment the auditing assumes you also have to request logging active, i.e. that a "current entry" is present when it tries to log an audit action. I'll update the component to automatically create an entry if this is not the case.
