### ISSUE TITLE
update screenshots and features list

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#70]
We have added a ton of great features thanks to extending yii2-debug, we should list them in the README.

Should also update the screenshots as the module looks a bit different now.  NOTE when adding images don't add them to the repo.  Instead, add them to an issue, and then just copy the link of the image.  That way they are stored on S3 and don't blow out the repo size with binary image data.

**Comment by Blizzke** [comment]
I wholeheartedly agree. We should definitely mention that we use the debug module for a lot of the functionality. Great idea with the images btw, I didn't know.

**Comment by cornernote** [comment]
see #75 for screenshots thead

**Comment by cornernote** [comment]
done
