### ISSUE TITLE
documentation for creating a panel

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#71]
Add some documentation that explains how to create a new panel.

Also, there is some docs on storing extra data, which I think is not very useful now because they cannot display it without a custom panel.  Perhaps there should be a panel for extra-data so that its easy to whack data in without needing to create a panel.

**Comment by Blizzke** [comment]
Yeah, I added a todo for this in the code but should've created an issue. I have a ton of extra data stored in one of my projects, I'll take care of this.

**Comment by cornernote** [comment]
I made a placeholder in the docs:

https://github.com/bedezign/yii2-audit/blob/master/docs/custom-panels.md

**Comment by cornernote** [comment]
done
