### ISSUE TITLE
Create clean set of migrations?

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#72]
With all the huge data changes and compatibility breaks we did, we might want to consider starting over with a nice clean set of migration scripts. Per @cornernote's suggestion we should definitely keep the old scripts in a subdirectory and update them to end up with the database format that we use in (i assume) 0.2
The last "old" migration script should probably batch insert the names of the new set into the migrations table, so that users can seamlessly continue with the rest

**Comment by cornernote** [comment]
yes please, new migrations would be awesome.  

we should also chuck a doc in the docs/ folder for info upgrading from 0.1-0.2
