### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#75]
This issues will be used to add screenshots for the documentation.

**Comment by cornernote** [comment]
this issue can be closed, as it's just for holding the images, the todo task is #70

**Comment by cornernote** [comment]
![image](https://cloud.githubusercontent.com/assets/51875/8369827/b70355ee-1bfe-11e5-9748-dd864f0500de.png)

**Comment by cornernote** [comment]
![image](https://cloud.githubusercontent.com/assets/51875/8369854/1c6492e0-1bff-11e5-8497-9424236e564e.png)

**Comment by cornernote** [comment]
![image](https://cloud.githubusercontent.com/assets/51875/8369879/857f70b0-1bff-11e5-8373-2d79e3b0c05d.png)
```
![image](https://cloud.githubusercontent.com/assets/51875/8369879/857f70b0-1bff-11e5-8373-2d79e3b0c05d.png)
```

**Comment by cornernote** [comment]
old screenshots from docs:

![Index example](docs/screenshots/audit-index.png?raw=true)
![View example](docs/screenshots/audit-view.png?raw=true)
![Diff example](docs/screenshots/audit-diff.png?raw=true)

```
![Index example](docs/screenshots/audit-index.png?raw=true)
![View example](docs/screenshots/audit-view.png?raw=true)
![Diff example](docs/screenshots/audit-diff.png?raw=true)
```

**Comment by cornernote** [comment]
![image](https://cloud.githubusercontent.com/assets/51875/8370372/149aa0de-1c06-11e5-8229-6fd53142b7c2.png)
```
![Custom Panel View](https://cloud.githubusercontent.com/assets/51875/8370372/149aa0de-1c06-11e5-8229-6fd53142b7c2.png)
```

**Comment by cornernote** [comment]
![Log Panel](https://cloud.githubusercontent.com/assets/51875/8370482/7987eeba-1c07-11e5-9fc1-cde26ed5cd64.png)
```
![Log Panel](https://cloud.githubusercontent.com/assets/51875/8370482/7987eeba-1c07-11e5-9fc1-cde26ed5cd64.png)
```

![Profiling Panel](https://cloud.githubusercontent.com/assets/51875/8370500/acde027c-1c07-11e5-82d4-6a4aa37afeb2.png)
```
![Profiling Panel](https://cloud.githubusercontent.com/assets/51875/8370500/acde027c-1c07-11e5-82d4-6a4aa37afeb2.png)
```

**Comment by cornernote** [comment]
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8370529/efbdccc6-1c07-11e5-997a-ec00df3ac3dd.png)

```
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8370529/efbdccc6-1c07-11e5-997a-ec00df3ac3dd.png)
```

**Comment by cornernote** [comment]
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8370713/fd6482ea-1c0a-11e5-9581-96ef717d7e69.png)
![Logs Panel](https://cloud.githubusercontent.com/assets/51875/8370717/0e6e9134-1c0b-11e5-9840-17d1ece07b9a.png)
![Profile Panel](https://cloud.githubusercontent.com/assets/51875/8370722/20c571f4-1c0b-11e5-99c5-97f4cfb02394.png)

```
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8370713/fd6482ea-1c0a-11e5-9581-96ef717d7e69.png)
![Logs Panel](https://cloud.githubusercontent.com/assets/51875/8370717/0e6e9134-1c0b-11e5-9840-17d1ece07b9a.png)
![Profile Panel](https://cloud.githubusercontent.com/assets/51875/8370722/20c571f4-1c0b-11e5-99c5-97f4cfb02394.png)
```

**Comment by cornernote** [comment]
![Trail Panel](https://cloud.githubusercontent.com/assets/51875/8372013/2fcf5f44-1c1e-11e5-8218-8fa6abf193c0.png)
```
![Trail Panel](https://cloud.githubusercontent.com/assets/51875/8372013/2fcf5f44-1c1e-11e5-8218-8fa6abf193c0.png)
```

**Comment by cornernote** [comment]
![Audit Trail Application View](https://cloud.githubusercontent.com/assets/51875/8373348/24c00646-1c2b-11e5-8266-df1b17cdfdb7.png)
```
![Audit Trail Application View](https://cloud.githubusercontent.com/assets/51875/8373348/24c00646-1c2b-11e5-8266-df1b17cdfdb7.png)
```

**Comment by cornernote** [comment]
![Audit Trail Application View](https://cloud.githubusercontent.com/assets/51875/8373390/72c8023a-1c2b-11e5-9589-02fe6974ee45.png)
```
![Audit Trail Application View](https://cloud.githubusercontent.com/assets/51875/8373390/72c8023a-1c2b-11e5-9589-02fe6974ee45.png)
```

**Comment by cornernote** [comment]
![Audit Entry View](https://cloud.githubusercontent.com/assets/51875/8395061/3b004aca-1d97-11e5-8b71-6787c662ea3e.png)
```
![Audit Entry View](https://cloud.githubusercontent.com/assets/51875/8395061/3b004aca-1d97-11e5-8b71-6787c662ea3e.png)
```

**Comment by cornernote** [comment]
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8395068/94b25018-1d97-11e5-9857-a7d3e151cc97.png)
```
![Database Panel](https://cloud.githubusercontent.com/assets/51875/8395068/94b25018-1d97-11e5-9857-a7d3e151cc97.png)
```

**Comment by cornernote** [comment]
![Log Panel](https://cloud.githubusercontent.com/assets/51875/8395070/af005528-1d97-11e5-8629-0a4fb3f9b4dd.png)
```
![Log Panel](https://cloud.githubusercontent.com/assets/51875/8395070/af005528-1d97-11e5-8629-0a4fb3f9b4dd.png)
```

**Comment by cornernote** [comment]
![Profiling Panel](https://cloud.githubusercontent.com/assets/51875/8395072/cc95d2a2-1d97-11e5-891e-05580d03fd7a.png)
```
![Profiling Panel](https://cloud.githubusercontent.com/assets/51875/8395072/cc95d2a2-1d97-11e5-891e-05580d03fd7a.png)
```

**Comment by cornernote** [comment]
![Error Panel](https://cloud.githubusercontent.com/assets/51875/8395074/f9b1d196-1d97-11e5-874d-829c095aead8.png)
```
![Error Panel](https://cloud.githubusercontent.com/assets/51875/8395074/f9b1d196-1d97-11e5-874d-829c095aead8.png)
```

**Comment by cornernote** [comment]
![Javascript Panel](https://cloud.githubusercontent.com/assets/51875/8395077/25f75e88-1d98-11e5-9ade-32a5e9b16511.png)
```
![Javascript Panel](https://cloud.githubusercontent.com/assets/51875/8395077/25f75e88-1d98-11e5-9ade-32a5e9b16511.png)
```

**Comment by Blizzke** [comment]
![Audit Dashboard](https://cloud.githubusercontent.com/assets/231572/8447805/bbb6de94-1fbe-11e5-83eb-6c08795d5909.png)

(small)
```
![Audit Dashboard](https://cloud.githubusercontent.com/assets/231572/8447805/bbb6de94-1fbe-11e5-83eb-6c08795d5909.png)
```

**Comment by cornernote** [comment]
![Mail Grid](https://cloud.githubusercontent.com/assets/51875/8636518/30146f00-28a6-11e5-958c-8ffff43fcd75.png)

![Mail View](https://cloud.githubusercontent.com/assets/51875/8636514/16069322-28a6-11e5-91d1-cf1d5f667f8d.png)

```
![Mail Grid](https://cloud.githubusercontent.com/assets/51875/8636518/30146f00-28a6-11e5-958c-8ffff43fcd75.png)
![Mail View](https://cloud.githubusercontent.com/assets/51875/8636514/16069322-28a6-11e5-91d1-cf1d5f667f8d.png)
```

**Comment by cornernote** [comment]
![Error Grid](https://cloud.githubusercontent.com/assets/51875/8636528/9f8b2338-28a6-11e5-8bd7-bb4325192b65.png)
![Error View](https://cloud.githubusercontent.com/assets/51875/8636531/b30540a6-28a6-11e5-9249-39783d098943.png)

```
![Error Grid](https://cloud.githubusercontent.com/assets/51875/8636528/9f8b2338-28a6-11e5-8bd7-bb4325192b65.png)
![Error View](https://cloud.githubusercontent.com/assets/51875/8636531/b30540a6-28a6-11e5-9249-39783d098943.png)
```

**Comment by cornernote** [comment]
![Trail Grid](https://cloud.githubusercontent.com/assets/51875/8636534/f3886234-28a6-11e5-9796-93eae3e5eb62.png)
![Trail View](https://cloud.githubusercontent.com/assets/51875/8636535/fc9e95be-28a6-11e5-8344-fde6d314673a.png)

```
![Trail Grid](https://cloud.githubusercontent.com/assets/51875/8636534/f3886234-28a6-11e5-9796-93eae3e5eb62.png)
![Trail View](https://cloud.githubusercontent.com/assets/51875/8636535/fc9e95be-28a6-11e5-8344-fde6d314673a.png)
```

**Comment by cornernote** [comment]
![Javascript Grid](https://cloud.githubusercontent.com/assets/51875/8636539/29dfaa4a-28a7-11e5-8e9d-8d8b816edce9.png)
![Javascript View](https://cloud.githubusercontent.com/assets/51875/8636540/3315d558-28a7-11e5-8641-2ca237619ecc.png)

```
![Javascript Grid](https://cloud.githubusercontent.com/assets/51875/8636539/29dfaa4a-28a7-11e5-8e9d-8d8b816edce9.png)
![Javascript View](https://cloud.githubusercontent.com/assets/51875/8636540/3315d558-28a7-11e5-8641-2ca237619ecc.png)
```

**Comment by cornernote** [comment]
![Entry Grid](https://cloud.githubusercontent.com/assets/51875/8636542/6d6f92fc-28a7-11e5-9085-ce365d85906d.png)
```
![Entry Grid](https://cloud.githubusercontent.com/assets/51875/8636542/6d6f92fc-28a7-11e5-9085-ce365d85906d.png)
```

**Comment by Blizzke** [comment]
![cURL Headers](https://cloud.githubusercontent.com/assets/231572/8657510/5e747b12-299e-11e5-948d-8787ddd60260.png)

```
![cURL Headers](https://cloud.githubusercontent.com/assets/231572/8657510/5e747b12-299e-11e5-948d-8787ddd60260.png)
```

![cURL Info](https://cloud.githubusercontent.com/assets/231572/8657509/5e50bd80-299e-11e5-9cce-93c2ff9c7c60.png)

```
![cURL Info](https://cloud.githubusercontent.com/assets/231572/8657509/5e50bd80-299e-11e5-9cce-93c2ff9c7c60.png)
```

![cURL Log](https://cloud.githubusercontent.com/assets/231572/8657508/5e4f1048-299e-11e5-9a39-ccf321127fa1.png)

```
![cURL Log](https://cloud.githubusercontent.com/assets/231572/8657508/5e4f1048-299e-11e5-9a39-ccf321127fa1.png)
```

**Comment by cornernote** [comment]
![Cleanup Command](https://cloud.githubusercontent.com/assets/51875/8689333/83f1e17a-2ae5-11e5-8a8a-10ef30f23fdb.png)
```
![Cleanup Command](https://cloud.githubusercontent.com/assets/51875/8689333/83f1e17a-2ae5-11e5-8a8a-10ef30f23fdb.png)
```

**Comment by Blizzke** [comment]
![SOAP Error](https://cloud.githubusercontent.com/assets/231572/8715956/304daf2c-2b8a-11e5-8f9b-cfcd1bcb985f.png)

```
![SOAP Error](https://cloud.githubusercontent.com/assets/231572/8715956/304daf2c-2b8a-11e5-8f9b-cfcd1bcb985f.png)
```

![SOAP Info](https://cloud.githubusercontent.com/assets/231572/8715957/3061917c-2b8a-11e5-8d90-06747db7ad60.png)

```
![SOAP Info](https://cloud.githubusercontent.com/assets/231572/8715957/3061917c-2b8a-11e5-8d90-06747db7ad60.png)
```

![SOAP Result](https://cloud.githubusercontent.com/assets/231572/8715958/30674400-2b8a-11e5-9782-794c50c7e8f5.png)

```
![SOAP Result](https://cloud.githubusercontent.com/assets/231572/8715958/30674400-2b8a-11e5-9782-794c50c7e8f5.png)
```

**Comment by cornernote** [comment]
![Cleanup Command](https://cloud.githubusercontent.com/assets/51875/8716182/a1254650-2bcc-11e5-831f-4a377269128e.png)
```
![Cleanup Command](https://cloud.githubusercontent.com/assets/51875/8716182/a1254650-2bcc-11e5-831f-4a377269128e.png)
```
