### ISSUE TITLE
create extension page on yiiframework.com

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#76]
http://www.yiiframework.com/ext/create/

**Comment by cornernote** [comment]
once done i think we should change the `powered by yii2` badge to link to the extension

**Comment by Blizzke** [comment]
http://www.yiiframework.com/extension/yii2-audit/

**Comment by cornernote** [comment]
updated the badge, yeah once we get the new screenshots in the readme just copy/paste the readme (and update links)

**Comment by Blizzke** [comment]
Updated the yii extension page. 
The problem is the Yii site doesn't do large images very well and they don't support the resizing notation.
I am leaning towards adding smaller versions of all images just for there, but that would mean more update work on a change. What are you opinions?

**Comment by cornernote** [comment]
can you manually do an img tag with style="max-width:100%" ?

I did this via inspection tool, not sure if it will work when updating the extension page:
![image](https://cloud.githubusercontent.com/assets/51875/8395537/92a5be82-1db4-11e5-805a-c2b8119355d4.png)

**Comment by Blizzke** [comment]
Site was updated with smaller versions of the images, closing this.
