### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException. bedezign\yii2\audit\models\AuditEntry has no relation named "errors".

### ISSUE THREAD

**Issue by cloudswitch** [bedezign/yii2-audit#8]
1. in D:\wamp\www\yiicomm\vendor\yiisoft\yii2\db\BaseActiveRecord.php

if (!$relation instanceof ActiveQueryInterface) {
            if ($throwException) {
                throw new InvalidParamException(get_class($this) . ' has no relation named "' . $name . '".');
            } else {
                return null;
            }
        }

**Comment by Blizzke** [comment]
Sorry about that. The errors relation was renamed to remove the conflict with Yii's validation functionality and it seems I've overlooked one.

**Comment by cloudswitch** [comment]
no problem, you don't have to say always sorry, it's a super extension.
Can you please tell me: audit_entry: necessary? how can I turn it off? I'm only interested in audit_trail data. That's what I wanted to search for with filtering, and then came the error message. Is there a way to look only at audit_trail data as we can see audit_entry data (I mean like a grid)?
Thanks a lot!
BR
cs

**Comment by Blizzke** [comment]
Although the trail data is linked to the audit entries it is perfectly okay to use the `audit_trail` table separately and generate a grid based on its totality. We just don't have that functionality right now. It seems like something that could be very useful, but I don't really have an idea when and if I can find time for it. @MGHollander what do you think about this? A separate view for just the auditing trail alone?

**Comment by cloudswitch** [comment]
sorry, I'm a beginner, have you changed something now? I have updated with "composer update" (I hope it's the right way) but still the same error when trying to filter. Thx.

**Comment by Blizzke** [comment]
If you added the component with `'bedezign/yii2-audit: "*"` it should've been updated. But I'll put up a new release version, that should definitely solve it.

**Comment by MGHollander** [comment]
I personally would like to see all information linked so you can see a more detailed user activity. But it is possible to create a view with only the trail rules. But one thing to keep in mind is that the user_id is not saved in the trail but in the entry table. I'll work on a view with only the trail record. But I'll save the other data to for the full picture.

**Comment by Blizzke** [comment]
Everything is hinged to the entry-record and I fully agree with @MGHollander in that it should stay like that. 
But I modified the trail code so that it will create an entry (only if needed in case you don't have the regular request logging enabled). Basically only using audit trails will work perfectly and will create the associated entry record when needed. I don't see any issues there. (Although I now realise that the entry record is not finalised in that case, not huge problem but not very clean)

So what remains is that we should add an extra view where we render out the `audit_trail`-table as a whole and we display the `User ID` via the entry relation as opposed to starting form the entry list.

**Comment by MGHollander** [comment]
On second thoughts it may be good to set the `entry_id` in the `audit_trail` table to `NULL` if request logging is off. Then the whole finalizing part isn't necessary. Developers choice don't you think?

**Comment by Blizzke** [comment]
It's a possibility but then we'd have to duplicate the user_id like you mentioned. 
If you feel ok with that then we can handle it in that way and only combine them if they have request logging enabled.

**Comment by MGHollander** [comment]
Like I said, it's a developers own choice. A duplicate `user_id` to link an `audit_trail` entry to a user if request logging is off doesn't bother me. I just didn't think of it :-)

**Comment by Blizzke** [comment]
Since `audit_entry` can already be `null` in the `audit_trail`-table, I guess we just have to add the `user_id`column and modify the code accordingly. And add a view that sticks with the trail table only of course :)

**Comment by MGHollander** [comment]
I agree.
