### ISSUE TITLE
too many URL fields in the audit_entry

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#82]
the data is all in the Request panel, we track route on create, i think thats enough

i think we can remove `url`, `redirect`, `referrer`

what are your thoughts?

**Comment by Blizzke** [comment]
As far as I can see we don't have that information anywhere else besides there. I would definitely like the full `url` somewhere. Perhaps we can add a URL panel that tracks those and that you can enable/disable? Wouldn't having a "redirect" status field be handy to indicate that the user was redirect at the end of the request?

**Comment by Blizzke** [comment]
Seems that we have the information somewhere else too. I'll remove them
