### ISSUE TITLE
Search by username/identifier?

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#84]
We have a nice callback to allow us to output a user identifier/username instead of the ID, but what about the other way? I'd like to add functionality to do the reverse so that we can type the identifier in the grid filter and search for the correct ID.

We can accomplish this by either reusing the same callback and spec'ing it that "if you get a string, return a set of IDs that match and if you get a number return a string" or add a second callback to do so.

Opinions? 
I lean more towards the first. It will make for a bit more implementation on the user side, but it's only the one callback they have to provide. It's not that clean though...

**Comment by cornernote** [comment]
I think a second cllback is easier to explain in the docs and can be named
mor appropriately

**Comment by Blizzke** [comment]
All good reasons. We'll do it like that then, don't be so lazy Steve! :)

**Comment by cornernote** [comment]
Can you also update the docs for this ?

**Comment by Blizzke** [comment]
[They were updated together with the new functionality](https://github.com/bedezign/yii2-audit/blob/master/docs/replacing-user_id.md#filtering-on-identifier)

**Comment by cornernote** [comment]
Ahh, ok.  I didnt see it.  Nice work!
