### ISSUE TITLE
indexes on created fields

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#85]
Should we add an index to the `created` fields?  This should make the graphs on the home page faster to load if you have a lot of data.

**Comment by Blizzke** [comment]
Every index we add slows down writes, possibly considerably. I think we should focus on having the information collected and written ASAP, not on making the viewer faster. I would consider adding an aggregation table for the entries that just logs a row per hour or so with the start and end entry-id, that allows us to select a lot faster. The aggregation can be done either on the cli or when the viewer is used.

**Comment by cornernote** [comment]
Good points. A better idea would be caching the counts for previous days.
