### ISSUE TITLE
Mail grid and view pages

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#88]
This is a really important issue to have in audit. I need to view and search mail, not just in an entry panel, but also on its own. This allows me to see all the mail the app is sending out.

I will create a new table, and change the way the mail panel writes it's data.

**Comment by Blizzke** [comment]
No objection here. Do you have an idea on how best to do it?

**Comment by cornernote** [comment]
Yeah, I had something similar in my mail module for yii1.  Now that yii2 handles mail all on its own (like a framework should) I wont be making a mail module, and the tracking will be moved to audit, which makes a lot more sense.

**Comment by cornernote** [comment]
todo
- download eml file
- fix tests

**Comment by cornernote** [comment]
done
