### ISSUE TITLE
Only show graphs for active panels

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#89]
Perhaps we should limit the visualised panels to only those that are actually active. 
In my specific case I am not using the mail panel and perhaps we shouldn't show it?
What do you guys think?

**Comment by cornernote** [comment]
Makes sense. We just need some logic for the col size depending on how many
panels there are

**Comment by Blizzke** [comment]
I was thinking that perhaps we can also implement a function to obtain an array with the data to render, then the view could ask each active panel for its graphic values and users would be able to add their own too.

**Comment by cornernote** [comment]
Yes, Great idea.  Maybe then keep them all a fixed size. If you have 5
panels one will be on its own. No big deal.

**Comment by Blizzke** [comment]
We can just make them all 3 or 4 columns wide and don't care about the wrapping, the bootstrap grid will take care of that on its own and it is allowed to add more than 12 columns on 1 row.
