### ISSUE TITLE
Audit Trail functionality without a linked entry

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#9]
@cloudswitch @MGHollander: I'm opening this issue to group any communication regarding the dedicated trail functionality requested in issue #8 

I've just done a commit on `master` that already adds the `user_id` to the table and fills it. The grid still needs to be done. For that reason I have not added a new release yet.

**Comment by MGHollander** [comment]
I created a grid for this issue. I'll update the readme in a view seconds.

**Comment by cloudswitch** [comment]
Many thanks guys for the enhancement! It's awesome!
