### ISSUE TITLE
ability to extend models

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#93]
the panel should have a `$model` property so the model can be extended (eg, trail, error, mail, javascript, others?)

**Comment by cornernote** [comment]
from @Blizzke : 

then you'd do this in the config and set
```
'audit/error' => ['class' => 'ErrorPanel', 'model' => 'my\class\Path']
```

**Comment by Blizzke** [comment]
Hmm, just realised: What about the search models for those? You'd have to modify them as well

**Comment by cornernote** [comment]
Yeah, another property i think.  You may want to only extend one or the
other (or both)

**Comment by cornernote** [comment]
since #110 this is no longer required, as you can simply extend the panel.
