### ISSUE TITLE
namespace for app in tests should be tests\app

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#94]
its causing my phpstorm to underline User because there is more than one `app\models\User`

**Comment by Blizzke** [comment]
If you would change the entire app for that, thats a lot of work with zero gain. Can't you just mark the tests folder as excluded from code analysis?

**Comment by cornernote** [comment]
should be a find/replace, then run the scripts

its not an urgent requirement, just something i'd like to do.  can even be after the 1.0 release.
