### ISSUE TITLE
Pjax breaks the `[+] EXPLAIN` functionality on the DB tab

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#97]
We need to figure some way to update the links and add a `data-pjax="0"` to them... perhaps a search & replace in the `DbPanel::getDetails()` before we return

**Comment by cornernote** [comment]
the fix is changing making them load on `ready` and another callback.

i was reading about this the other night.  i'll look after this one over the weekend.

**Comment by MGHollander** [comment]
You can set ``data-pjax=""`` as an empty attribute and it will act as a normal link.

**Comment by Blizzke** [comment]
Indeed, thats what I said in the initial comment:)
Problem is that the content is actually rendered by the debug module and that we get the "finalised" content back to put on screen. 
So we'll either have to search & replace before outputting the content, or like Brett said add a new `onReady`-handler and give all those links a `$('whateverselector').data('pjax', 0);`

**Comment by cornernote** [comment]
i like the idea of `$('.db-explain a').data('pjax', 0);` ... however I cant replicate any issue... the explain seems to work perfectly for me.

**Comment by cornernote** [comment]
heres how i tested - http://screencast.com/t/FOJlaIDRW

am I missing something ?

**Comment by Blizzke** [comment]
Hmm must be related to my custom layout then...Guess I'll have to test that

**Comment by cornernote** [comment]
i'll close this for now, re-open if you discover it to be an issue with audit.
