### ISSUE TITLE
logger.js in IE8

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#99]
object doesn't suppor this action
logger.js line 80 char 13

https://github.com/bedezign/yii2-audit/blob/master/src/web/assets/javascript/logger.js#L80

some potential solutions:
http://stackoverflow.com/questions/4819693/working-around-ie8s-broken-object-defineproperty-implementation
http://stackoverflow.com/questions/21175290/object-defineproperty-alternative-for-ie8

**Comment by Blizzke** [comment]
Yeah, I'm aware that it doesn't work in IE8. I usually test 8 through 11. 
However, since I have long since seized supporting anything pre IE9 - even that one is already 4 years old - I didn't feel like putting in the effort. At the change that it will break something for later browsers.

**Comment by cornernote** [comment]
As IE8 was the latest IE on winXP I thought it may be useful to have, depending on the complexity of the fix.  If it's too complex and risks breaking something else then lets just close this off.

**Comment by Blizzke** [comment]
Guess it can't hurt to take a look at it, just hate having to retest it in all those browsers :P 
I so miss my sauce labs subscription.
